#pragma once

#include "jyppx/cuda/types.h"

JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_query_runtime_info(JYPPX_CudaRuntimeInfo* out_info);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_runtime_version(int32_t* out_version);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_driver_version(int32_t* out_version);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_device_count(int32_t* out_device_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_device_info(int32_t ordinal, JYPPX_CudaDeviceInfo* out_info);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_current_device(int32_t* out_device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_set_device(int32_t device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_synchronize(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_reset(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_attribute(int32_t device, int32_t attribute, int32_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_limit(int32_t limit, size_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_set_limit(int32_t limit, size_t value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_cache_config(int32_t* out_config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_set_cache_config(int32_t config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_shared_memory_config(int32_t* out_config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_set_shared_memory_config(int32_t config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_pci_bus_id(int32_t device, char* output_buffer, size_t output_buffer_size, size_t* out_required_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_by_pci_bus_id(const char* pci_bus_id, int32_t* out_device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_can_access_peer(int32_t device, int32_t peer_device, JYPPX_Boolean* out_can_access);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_p2p_attribute(int32_t attribute, int32_t source_device, int32_t destination_device, int32_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_enable_peer_access(int32_t peer_device, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_disable_peer_access(int32_t peer_device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_host_atomic_capabilities(uint32_t* capabilities, const int32_t* operations, uint32_t count, int32_t device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_p2p_atomic_capabilities(uint32_t* capabilities, const int32_t* operations, uint32_t count, int32_t source_device, int32_t destination_device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_choose_device(const JYPPX_CudaDeviceSelectionRequirements* requirements, int32_t* out_device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_dev_resource_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_execution_ctx_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_nv_sci_sync_attributes_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_register_async_notification_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_unregister_async_notification_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_device_flags(uint32_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_set_device_flags(uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_init_device(int32_t device, uint32_t device_flags, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_set_valid_devices(const int32_t* devices, uint32_t count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_memory_info(JYPPX_CudaMemoryInfo* out_info);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_last_error(int32_t* out_error_code);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_peek_at_last_error(int32_t* out_error_code);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_error_name(int32_t error_code, char* output_buffer, size_t output_buffer_size, size_t* out_required_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_error_string(int32_t error_code, char* output_buffer, size_t output_buffer_size, size_t* out_required_size);

JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_create(uint32_t flags, JYPPX_CudaStream** out_stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_priority_range(int32_t* out_least_priority, int32_t* out_greatest_priority);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_create_with_priority(uint32_t flags, int32_t priority, JYPPX_CudaStream** out_stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_flags(JYPPX_CudaStream* stream, uint32_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_priority(JYPPX_CudaStream* stream, int32_t* out_priority);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_id(JYPPX_CudaStream* stream, uint64_t* out_stream_id);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_device(JYPPX_CudaStream* stream, int32_t* out_device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_copy_attributes(JYPPX_CudaStream* destination, JYPPX_CudaStream* source);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_thread_exchange_stream_capture_mode(int32_t mode, int32_t* out_previous_mode);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_is_capturing(JYPPX_CudaStream* stream, int32_t* out_capture_status);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_capture_info(JYPPX_CudaStream* stream, int32_t* out_capture_status, uint64_t* out_capture_id);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_capture_summary_safe(JYPPX_CudaStream* stream, int32_t* out_capture_status, uint64_t* out_capture_id, JYPPX_Boolean* out_has_graph, size_t* out_dependency_count, JYPPX_Boolean* out_has_edge_data);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_update_capture_dependencies_safe(JYPPX_CudaStream* stream, const uintptr_t* dependencies, size_t dependency_count, uint32_t mode);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_attach_mem_async(JYPPX_CudaStream* stream, void* pointer, size_t length, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_attribute(JYPPX_CudaStream* stream, int32_t attribute, void* value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_set_attribute(JYPPX_CudaStream* stream, int32_t attribute, const void* value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_add_callback_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_begin_capture_to_graph_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_capture_info_ptsz_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_capture_info_v3_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_dev_resource_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_update_capture_dependencies_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_update_capture_dependencies_ptsz_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_update_capture_dependencies_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_query(JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_wait_event(JYPPX_CudaStream* stream, JYPPX_CudaEvent* event_handle, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_synchronize(JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_destroy(JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_begin_capture(JYPPX_CudaStream* stream, int32_t mode);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_end_capture(JYPPX_CudaStream* stream, JYPPX_CudaGraph** out_graph);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_func_get_attributes(const void* function, JYPPX_CudaFuncAttributes* out_attributes);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_func_get_name(const void* function, char* output_buffer, size_t output_buffer_size, size_t* out_required_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_func_get_param_count(const void* function, size_t* out_param_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_func_get_param_info(const void* function, size_t parameter_index, size_t* out_parameter_offset, size_t* out_parameter_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_func_set_attribute(const void* function, int32_t attribute, int32_t value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_func_set_cache_config(const void* function, int32_t cache_config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_func_set_shared_mem_config(const void* function, int32_t config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_launch_kernel(const void* function, JYPPX_CudaDim3 grid_dim, JYPPX_CudaDim3 block_dim, void** arguments, size_t shared_memory_bytes, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_launch_kernel_ex(const JYPPX_CudaLaunchConfig* config, const void* function, void** arguments);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_launch_cooperative_kernel(const void* function, JYPPX_CudaDim3 grid_dim, JYPPX_CudaDim3 block_dim, void** arguments, size_t shared_memory_bytes, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_launch_host_func_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_launch_host_func_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_occupancy_available_dynamic_smem_per_block(size_t* out_dynamic_shared_memory_size, const void* function, int32_t num_blocks, int32_t block_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_occupancy_max_active_blocks_per_multiprocessor(int32_t* out_num_blocks, const void* function, int32_t block_size, size_t dynamic_shared_memory_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_occupancy_max_active_blocks_per_multiprocessor_with_flags(int32_t* out_num_blocks, const void* function, int32_t block_size, size_t dynamic_shared_memory_size, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_occupancy_max_potential_cluster_size(int32_t* out_cluster_size, const void* function, const JYPPX_CudaLaunchConfig* config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_occupancy_max_active_clusters(int32_t* out_num_clusters, const void* function, const JYPPX_CudaLaunchConfig* config);

JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_create(uint32_t flags, JYPPX_CudaGraph** out_graph);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_clone(JYPPX_CudaGraph* graph, JYPPX_CudaGraph** out_clone);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_child_graph_node_safe(JYPPX_CudaGraph* graph, JYPPX_CudaGraph* child_graph, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_child_graph_node_after_safe(JYPPX_CudaGraph* graph, uintptr_t dependency_node, JYPPX_CudaGraph* child_graph, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_child_graph_node_has_embedded_graph_safe(uintptr_t node, JYPPX_Boolean* out_has_graph);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_child_graph_node_get_node_count_safe(uintptr_t node, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_child_graph_node_get_root_node_count_safe(uintptr_t node, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_child_graph_node_get_edge_count_safe(uintptr_t node, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_child_graph_node_set_params_safe(JYPPX_CudaGraphExec* graph_exec, uintptr_t node, JYPPX_CudaGraph* child_graph);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_update_copied_metadata_safe(JYPPX_CudaGraphExec* graph_exec, JYPPX_CudaGraph* graph, int32_t* out_result, JYPPX_Boolean* out_has_error_node, int32_t* out_error_node_type, JYPPX_Boolean* out_has_error_from_node, int32_t* out_error_from_node_type);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_instantiate_with_params_safe(JYPPX_CudaGraph* graph, uint64_t flags, JYPPX_CudaGraphExec** out_graph_exec, int32_t* out_result, JYPPX_Boolean* out_has_error_node, int32_t* out_error_node_type);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_instantiate_with_params_on_stream_safe(JYPPX_CudaGraph* graph, uint64_t flags, JYPPX_CudaStream* upload_stream, JYPPX_CudaGraphExec** out_graph_exec, int32_t* out_result, JYPPX_Boolean* out_has_error_node, int32_t* out_error_node_type);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_kernel_node_copy_attributes_safe(uintptr_t destination_node, uintptr_t source_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_memset_node_safe(JYPPX_CudaGraph* graph, JYPPX_CudaMemory* destination, uint32_t value, size_t count, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_memset_node_after_safe(JYPPX_CudaGraph* graph, uintptr_t dependency_node, JYPPX_CudaMemory* destination, uint32_t value, size_t count, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_memset_node_set_params_safe(JYPPX_CudaGraphExec* graph_exec, uintptr_t node, JYPPX_CudaMemory* destination, uint32_t value, size_t count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_destroy_node_owner_scoped_safe(JYPPX_CudaGraph* graph, uintptr_t node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_kernel_node_get_params_snapshot_safe(uintptr_t node, JYPPX_CudaGraphKernelNodeParamsSnapshot* out_snapshot);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_host_node_get_params_snapshot_safe(uintptr_t node, JYPPX_CudaGraphHostNodeParamsSnapshot* out_snapshot);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_mem_alloc_node_get_params_snapshot_safe(uintptr_t node, JYPPX_CudaGraphMemAllocNodeParamsSnapshot* out_snapshot);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_mem_free_node_get_params_snapshot_safe(uintptr_t node, JYPPX_CudaGraphMemFreeNodeParamsSnapshot* out_snapshot);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_external_semaphore_signal_node_get_params_snapshot_safe(uintptr_t node, JYPPX_CudaGraphExternalSemaphoreNodeParamsSnapshot* out_snapshot);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_external_semaphore_wait_node_get_params_snapshot_safe(uintptr_t node, JYPPX_CudaGraphExternalSemaphoreNodeParamsSnapshot* out_snapshot);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_node_count(JYPPX_CudaGraph* graph, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_root_node_count(JYPPX_CudaGraph* graph, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_edge_count(JYPPX_CudaGraph* graph, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_instantiate(JYPPX_CudaGraph* graph, uint64_t flags, JYPPX_CudaGraphExec** out_graph_exec);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_get_flags(JYPPX_CudaGraphExec* graph_exec, uint64_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_upload(JYPPX_CudaGraphExec* graph_exec, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_launch(JYPPX_CudaGraphExec* graph_exec, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_destroy(JYPPX_CudaGraphExec* graph_exec);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_destroy(JYPPX_CudaGraph* graph);

JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_logs_get_current_cursor_safe(uint32_t* out_iterator);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_logs_dump_to_memory_safe(JYPPX_Boolean use_iterator, uint32_t iterator, char* output_buffer, size_t output_buffer_size, size_t* out_written_size, uint32_t* out_next_iterator);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_logs_dump_to_file_safe(JYPPX_Boolean use_iterator, uint32_t iterator, const char* path, uint32_t* out_next_iterator);

JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_create(uint32_t flags, JYPPX_CudaEvent** out_event);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_get_flags(JYPPX_CudaEvent* event_handle, uint32_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_query(JYPPX_CudaEvent* event_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_record(JYPPX_CudaEvent* event_handle, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_record_with_flags(JYPPX_CudaEvent* event_handle, JYPPX_CudaStream* stream, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_synchronize(JYPPX_CudaEvent* event_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_elapsed_time(JYPPX_CudaEvent* start_event, JYPPX_CudaEvent* end_event, float* out_milliseconds);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_destroy(JYPPX_CudaEvent* event_handle);

JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_alloc(size_t size, JYPPX_CudaMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_alloc_async(size_t size, JYPPX_CudaStream* stream, JYPPX_CudaMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_alloc_from_pool_async(size_t size, uint64_t pool_handle, JYPPX_CudaStream* stream, JYPPX_CudaMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_alloc_managed(size_t size, uint32_t flags, JYPPX_CudaMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_get_size(JYPPX_CudaMemory* memory, size_t* out_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_get_device_pointer(JYPPX_CudaMemory* memory, void** out_pointer);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_get_pointer_attributes(JYPPX_CudaMemory* memory, JYPPX_CudaPointerAttributes* out_attributes);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_copy_from_host(JYPPX_CudaMemory* memory, const void* source, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_copy_to_host(JYPPX_CudaMemory* memory, void* destination, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_copy_from_host_async(JYPPX_CudaMemory* memory, const void* source, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_copy_to_host_async(JYPPX_CudaMemory* memory, void* destination, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_copy_device_to_device(JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_copy_device_to_device_async(JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_copy_default(JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_copy_default_async(JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_copy_peer(JYPPX_CudaMemory* destination, int32_t destination_device, JYPPX_CudaMemory* source, int32_t source_device, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_copy_peer_async(JYPPX_CudaMemory* destination, int32_t destination_device, JYPPX_CudaMemory* source, int32_t source_device, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_memset(JYPPX_CudaMemory* memory, int32_t value, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_memset_async(JYPPX_CudaMemory* memory, int32_t value, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_prefetch_async(JYPPX_CudaMemory* memory, size_t size, int32_t destination_device, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_prefetch_range_async(JYPPX_CudaMemory* memory, size_t offset, size_t count, int32_t destination_device, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_advise(JYPPX_CudaMemory* memory, size_t size, int32_t advice, int32_t device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_advise_range(JYPPX_CudaMemory* memory, size_t offset, size_t count, int32_t advice, int32_t device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_range_get_attribute(JYPPX_CudaMemory* memory, size_t offset, size_t count, int32_t attribute, int32_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_range_get_attributes(JYPPX_CudaMemory* memory, size_t offset, size_t count, const int32_t* attributes, size_t attribute_count, JYPPX_CudaMemRangeAttributeValue* out_values);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_range_get_accessed_by_count(JYPPX_CudaMemory* memory, size_t offset, size_t count, size_t* out_device_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_range_copy_accessed_by_devices(JYPPX_CudaMemory* memory, size_t offset, size_t count, int32_t* output_devices, size_t output_device_count, size_t* out_required_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_free_async(JYPPX_CudaMemory* memory, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_free(JYPPX_CudaMemory* memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_malloc_host(size_t size, JYPPX_CudaPinnedMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_host_unregister(JYPPX_CudaPinnedMemory* memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_malloc_3d(size_t width_bytes, size_t height, size_t depth, JYPPX_CudaPitchedMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_async(void* destination, const void* source, size_t size, int32_t kind, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_async(void* destination, size_t destination_pitch, const void* source, size_t source_pitch, size_t width_bytes, size_t height, int32_t kind, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d(void* destination, size_t destination_pitch, const void* source, size_t source_pitch, size_t width_bytes, size_t height, size_t depth, int32_t kind);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_async(void* destination, size_t destination_pitch, const void* source, size_t source_pitch, size_t width_bytes, size_t height, size_t depth, int32_t kind, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_to_symbol(const void* symbol, const void* source, size_t count, size_t offset, int32_t kind);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_from_symbol(void* destination, const void* symbol, size_t count, size_t offset, int32_t kind);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_to_symbol_async(const void* symbol, const void* source, size_t count, size_t offset, int32_t kind, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_from_symbol_async(void* destination, const void* symbol, size_t count, size_t offset, int32_t kind, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_peer(const JYPPX_CudaMemcpy3DPeerParams* parameters);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_peer_async(const JYPPX_CudaMemcpy3DPeerParams* parameters, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_batch_async(void** destinations, const void** sources, const size_t* sizes, size_t count, const JYPPX_CudaMemcpyAttributes* attributes, const size_t* attribute_indices, size_t attribute_count, size_t* out_fail_index, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_batch_async(size_t operation_count, const JYPPX_CudaMemcpy3DBatchOp* operations, size_t* out_fail_index, uint64_t flags, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_with_attributes_async(void* destination, const void* source, size_t size, const JYPPX_CudaMemcpyAttributes* attributes, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_with_attributes_async(const JYPPX_CudaMemcpy3DBatchOp* operation, uint64_t flags, JYPPX_CudaStream* stream);

JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_pool_create(int32_t device, uint64_t* out_pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_pool_destroy(uint64_t pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_default_memory_pool(int32_t device, uint64_t* out_pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_current_memory_pool(int32_t device, uint64_t* out_pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_set_current_memory_pool(int32_t device, uint64_t pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_pool_get_attribute(uint64_t pool_handle, int32_t attribute, int64_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_pool_set_attribute(uint64_t pool_handle, int32_t attribute, int64_t value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_pool_trim_to(uint64_t pool_handle, size_t min_bytes_to_keep);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_pool_set_access(uint64_t pool_handle, int32_t device, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memory_pool_get_access(uint64_t pool_handle, int32_t device, uint32_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_get_default_mem_pool(const JYPPX_CudaMemLocation* location, int32_t allocation_type, uint64_t* out_pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_get_mem_pool(const JYPPX_CudaMemLocation* location, int32_t allocation_type, uint64_t* out_pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_set_mem_pool(const JYPPX_CudaMemLocation* location, int32_t allocation_type, uint64_t pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_export_to_shareable_handle(uint64_t pool_handle, int32_t handle_type, uint32_t flags, void* shareable_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_import_from_shareable_handle(void* shareable_handle, int32_t handle_type, uint32_t flags, uint64_t* out_pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_export_pointer(void* pointer, JYPPX_CudaMemPoolPtrExportData* out_export_data);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_import_pointer(uint64_t pool_handle, const JYPPX_CudaMemPoolPtrExportData* export_data, void** out_pointer);

JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_alloc(size_t width_bytes, size_t height, JYPPX_CudaPitchedMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_get_info(JYPPX_CudaPitchedMemory* memory, JYPPX_CudaPitchedMemoryInfo* out_info);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_from_host_2d(JYPPX_CudaPitchedMemory* memory, const void* source, size_t source_pitch, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_to_host_2d(JYPPX_CudaPitchedMemory* memory, void* destination, size_t destination_pitch, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_device_to_device_2d(JYPPX_CudaPitchedMemory* destination, JYPPX_CudaPitchedMemory* source, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_from_host_2d_async(JYPPX_CudaPitchedMemory* memory, const void* source, size_t source_pitch, size_t width_bytes, size_t height, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_to_host_2d_async(JYPPX_CudaPitchedMemory* memory, void* destination, size_t destination_pitch, size_t width_bytes, size_t height, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_device_to_device_2d_async(JYPPX_CudaPitchedMemory* destination, JYPPX_CudaPitchedMemory* source, size_t width_bytes, size_t height, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_from_host_3d(JYPPX_CudaPitchedMemory* memory, const void* source, size_t source_pitch, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_to_host_3d(JYPPX_CudaPitchedMemory* memory, void* destination, size_t destination_pitch, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_device_to_device_3d(JYPPX_CudaPitchedMemory* destination, JYPPX_CudaPitchedMemory* source, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_from_host_3d_async(JYPPX_CudaPitchedMemory* memory, const void* source, size_t source_pitch, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_to_host_3d_async(JYPPX_CudaPitchedMemory* memory, void* destination, size_t destination_pitch, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_copy_device_to_device_3d_async(JYPPX_CudaPitchedMemory* destination, JYPPX_CudaPitchedMemory* source, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_memset_2d(JYPPX_CudaPitchedMemory* memory, int32_t value, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_memset_2d_async(JYPPX_CudaPitchedMemory* memory, int32_t value, size_t width_bytes, size_t height, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_memset_3d(JYPPX_CudaPitchedMemory* memory, int32_t value, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_memset_3d_async(JYPPX_CudaPitchedMemory* memory, int32_t value, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pitched_memory_free(JYPPX_CudaPitchedMemory* memory);

JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_malloc_array(const JYPPX_CudaChannelFormatDesc* descriptor, size_t width, size_t height, uint32_t flags, JYPPX_CudaArray** out_array);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_malloc_3d_array(const JYPPX_CudaChannelFormatDesc* descriptor, const JYPPX_CudaArrayExtent* extent, uint32_t flags, JYPPX_CudaArray** out_array);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_free_array(JYPPX_CudaArray* array);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_array_get_plane(JYPPX_CudaArray* array, uint32_t plane_index, JYPPX_CudaArray** out_plane);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_array_get_info(JYPPX_CudaArray* array, JYPPX_CudaArrayInfo* out_info);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_array_get_channel_desc(JYPPX_CudaArray* array, JYPPX_CudaChannelFormatDesc* out_descriptor);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_array_get_memory_requirements(JYPPX_CudaArray* array, int32_t device, JYPPX_CudaArrayMemoryRequirements* out_requirements);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_array_get_sparse_properties(JYPPX_CudaArray* array, JYPPX_CudaArraySparseProperties* out_properties);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_texture_1d_linear_max_width(const JYPPX_CudaChannelFormatDesc* descriptor, int32_t device, size_t* out_max_width);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_to_array(JYPPX_CudaArray* destination, size_t destination_x_bytes, size_t destination_y, const void* source, size_t byte_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_from_array(void* destination, JYPPX_CudaArray* source, size_t source_x_bytes, size_t source_y, size_t byte_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_array_to_array(JYPPX_CudaArray* destination, size_t destination_x_bytes, size_t destination_y, JYPPX_CudaArray* source, size_t source_x_bytes, size_t source_y, size_t byte_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_to_array_async(JYPPX_CudaArray* destination, size_t destination_x_bytes, size_t destination_y, const void* source, size_t byte_count, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_from_array_async(void* destination, JYPPX_CudaArray* source, size_t source_x_bytes, size_t source_y, size_t byte_count, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_to_array(JYPPX_CudaArray* destination, size_t destination_x_bytes, size_t destination_y, const void* source, size_t source_pitch, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_from_array(void* destination, size_t destination_pitch, JYPPX_CudaArray* source, size_t source_x_bytes, size_t source_y, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_array_to_array(JYPPX_CudaArray* destination, size_t destination_x_bytes, size_t destination_y, JYPPX_CudaArray* source, size_t source_x_bytes, size_t source_y, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_to_array_async(JYPPX_CudaArray* destination, size_t destination_x_bytes, size_t destination_y, const void* source, size_t source_pitch, size_t width_bytes, size_t height, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_from_array_async(void* destination, size_t destination_pitch, JYPPX_CudaArray* source, size_t source_x_bytes, size_t source_y, size_t width_bytes, size_t height, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_to_array(JYPPX_CudaArray* destination, size_t destination_x_bytes, size_t destination_y, size_t destination_z, const void* source, size_t source_pitch, size_t source_width_bytes, size_t source_height, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_from_array(void* destination, size_t destination_pitch, size_t destination_width_bytes, size_t destination_height, JYPPX_CudaArray* source, size_t source_x_bytes, size_t source_y, size_t source_z, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_array_to_array(JYPPX_CudaArray* destination, size_t destination_x_bytes, size_t destination_y, size_t destination_z, JYPPX_CudaArray* source, size_t source_x_bytes, size_t source_y, size_t source_z, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_to_array_async(JYPPX_CudaArray* destination, size_t destination_x_bytes, size_t destination_y, size_t destination_z, const void* source, size_t source_pitch, size_t source_width_bytes, size_t source_height, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_from_array_async(void* destination, size_t destination_pitch, size_t destination_width_bytes, size_t destination_height, JYPPX_CudaArray* source, size_t source_x_bytes, size_t source_y, size_t source_z, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_array_to_array_async(JYPPX_CudaArray* destination, size_t destination_x_bytes, size_t destination_y, size_t destination_z, JYPPX_CudaArray* source, size_t source_x_bytes, size_t source_y, size_t source_z, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_malloc_mipmapped_array(const JYPPX_CudaChannelFormatDesc* descriptor, const JYPPX_CudaArrayExtent* extent, uint32_t level_count, uint32_t flags, JYPPX_CudaMipmappedArray** out_array);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_free_mipmapped_array(JYPPX_CudaMipmappedArray* array);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_mipmapped_array_level_info(JYPPX_CudaMipmappedArray* array, uint32_t level, JYPPX_CudaArrayInfo* out_info);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mipmapped_array_get_memory_requirements(JYPPX_CudaMipmappedArray* array, int32_t device, JYPPX_CudaArrayMemoryRequirements* out_requirements);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mipmapped_array_get_sparse_properties(JYPPX_CudaMipmappedArray* array, JYPPX_CudaArraySparseProperties* out_properties);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_ctx_reset_persisting_l2_cache(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_flush_gpu_direct_rdma_writes(int32_t target, int32_t scope);

JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pinned_memory_alloc(size_t size, JYPPX_CudaPinnedMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pinned_memory_alloc_with_flags(size_t size, uint32_t flags, JYPPX_CudaPinnedMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pinned_memory_register(void* pointer, size_t size, uint32_t flags, JYPPX_CudaPinnedMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pinned_memory_get_size(JYPPX_CudaPinnedMemory* memory, size_t* out_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pinned_memory_get_flags(JYPPX_CudaPinnedMemory* memory, uint32_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pinned_memory_get_host_pointer(JYPPX_CudaPinnedMemory* memory, void** out_pointer);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pinned_memory_get_mapped_device_pointer(JYPPX_CudaPinnedMemory* memory, void** out_pointer);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pinned_memory_free(JYPPX_CudaPinnedMemory* memory);

/* BEGIN CUDA TWENTY-THIRD BATCH GENERATED DECLARATIONS */
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_p2_p_attribute(int32_t attribute, int32_t source_device, int32_t destination_device, int32_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_shared_mem_config(int32_t* out_config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_set_shared_mem_config(int32_t config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_stream_priority_range(int32_t* out_least_priority, int32_t* out_greatest_priority);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_elapsed_time_v2(JYPPX_CudaEvent* start_event, JYPPX_CudaEvent* end_event, float* out_milliseconds);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_nodes(JYPPX_CudaGraph* graph, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_root_nodes(JYPPX_CudaGraph* graph, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_edges(JYPPX_CudaGraph* graph, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_instantiate_with_flags(JYPPX_CudaGraph* graph, uint64_t flags, JYPPX_CudaGraphExec** out_graph_exec);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_launch(JYPPX_CudaGraphExec* graph_exec, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_upload(JYPPX_CudaGraphExec* graph_exec, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_child_graph_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_dependencies_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_dependencies_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_empty_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_event_record_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_event_wait_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_external_semaphores_signal_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_external_semaphores_wait_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_host_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_kernel_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_mem_alloc_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_memcpy_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_memcpy_node1_d_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_memcpy_node_from_symbol_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_memcpy_node_to_symbol_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_mem_free_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_memset_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_add_node_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_child_graph_node_get_graph_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_conditional_handle_create_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_conditional_handle_create_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_debug_dot_print_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_destroy_node_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_event_record_node_get_event_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_event_record_node_set_event_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_event_wait_node_get_event_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_event_wait_node_set_event_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_child_graph_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_event_record_node_set_event_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_event_wait_node_set_event_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_external_semaphores_signal_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_external_semaphores_wait_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_get_id_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_host_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_kernel_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_memcpy_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_memcpy_node_set_params1_d_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_memcpy_node_set_params_from_symbol_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_memcpy_node_set_params_to_symbol_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_memset_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_exec_update_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_external_semaphores_signal_node_get_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_external_semaphores_signal_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_external_semaphores_wait_node_get_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_external_semaphores_wait_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_get_edges_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_get_id_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_host_node_get_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_host_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graphics_map_resources_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graphics_resource_get_mapped_mipmapped_array_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graphics_resource_get_mapped_pointer_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graphics_resource_set_map_flags_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graphics_sub_resource_get_mapped_array_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graphics_unmap_resources_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graphics_unregister_resource_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_instantiate_with_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_cuda_graph_kernel_node_copy_attributes_deferred(void);
/* END CUDA TWENTY-THIRD BATCH GENERATED DECLARATIONS */

/* BEGIN CUDA TWENTY-FOURTH BATCH GENERATED DECLARATIONS */
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_runtime_get_version(int32_t* out_version);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_driver_get_version(int32_t* out_version);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_count(int32_t* out_device_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_properties(int32_t ordinal, JYPPX_CudaDeviceInfo* out_info);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_current(int32_t* out_device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_set_current(int32_t device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_synchronize_v2(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_reset_v2(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_attribute_v2(int32_t device, int32_t attribute, int32_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_limit_v2(int32_t limit, size_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_set_limit_v2(int32_t limit, size_t value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_cache_config_v2(int32_t* out_config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_set_cache_config_v2(int32_t config);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_pci_bus_id_v2(int32_t device, char* output_buffer, size_t output_buffer_size, size_t* out_required_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_by_pci_bus_id_v2(const char* pci_bus_id, int32_t* out_device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_can_access_peer_v2(int32_t device, int32_t peer_device, JYPPX_Boolean* out_can_access);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_enable_peer_access_v2(int32_t peer_device, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_disable_peer_access_v2(int32_t peer_device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_p2p_attribute_v2(int32_t attribute, int32_t source_device, int32_t destination_device, int32_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_flags_v2(uint32_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_set_flags_v2(uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_get_info(JYPPX_CudaMemoryInfo* out_info);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_malloc(size_t size, JYPPX_CudaMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_malloc_managed(size_t size, uint32_t flags, JYPPX_CudaMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_malloc_async(size_t size, JYPPX_CudaStream* stream, JYPPX_CudaMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_malloc_from_pool_async(size_t size, uint64_t pool_handle, JYPPX_CudaStream* stream, JYPPX_CudaMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_get_size(JYPPX_CudaMemory* memory, size_t* out_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_get_device_pointer(JYPPX_CudaMemory* memory, void** out_pointer);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_pointer_get_attributes(JYPPX_CudaMemory* memory, JYPPX_CudaPointerAttributes* out_attributes);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_host_to_device(JYPPX_CudaMemory* memory, const void* source, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_device_to_host(JYPPX_CudaMemory* memory, void* destination, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_host_to_device_async(JYPPX_CudaMemory* memory, const void* source, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_device_to_host_async(JYPPX_CudaMemory* memory, void* destination, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_device_to_device(JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_device_to_device_async(JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_default(JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_default_async(JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_peer(JYPPX_CudaMemory* destination, int32_t destination_device, JYPPX_CudaMemory* source, int32_t source_device, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_peer_async(JYPPX_CudaMemory* destination, int32_t destination_device, JYPPX_CudaMemory* source, int32_t source_device, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memset(JYPPX_CudaMemory* memory, int32_t value, size_t size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memset_async(JYPPX_CudaMemory* memory, int32_t value, size_t size, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_prefetch_async(JYPPX_CudaMemory* memory, size_t size, int32_t destination_device, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_advise(JYPPX_CudaMemory* memory, size_t size, int32_t advice, int32_t device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_free(JYPPX_CudaMemory* memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_free_async(JYPPX_CudaMemory* memory, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_create(int32_t device, uint64_t* out_pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_destroy(uint64_t pool_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_get_attribute(uint64_t pool_handle, int32_t attribute, int64_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_set_attribute(uint64_t pool_handle, int32_t attribute, int64_t value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_trim_to(uint64_t pool_handle, size_t min_bytes_to_keep);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_set_access(uint64_t pool_handle, int32_t device, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_pool_get_access(uint64_t pool_handle, int32_t device, uint32_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_malloc_pitch(size_t width_bytes, size_t height, JYPPX_CudaPitchedMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_host_to_device(JYPPX_CudaPitchedMemory* memory, const void* source, size_t source_pitch, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_device_to_host(JYPPX_CudaPitchedMemory* memory, void* destination, size_t destination_pitch, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_device_to_device(JYPPX_CudaPitchedMemory* destination, JYPPX_CudaPitchedMemory* source, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_host_to_device_async(JYPPX_CudaPitchedMemory* memory, const void* source, size_t source_pitch, size_t width_bytes, size_t height, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_device_to_host_async(JYPPX_CudaPitchedMemory* memory, void* destination, size_t destination_pitch, size_t width_bytes, size_t height, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_2d_device_to_device_async(JYPPX_CudaPitchedMemory* destination, JYPPX_CudaPitchedMemory* source, size_t width_bytes, size_t height, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_host_to_device(JYPPX_CudaPitchedMemory* memory, const void* source, size_t source_pitch, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_device_to_host(JYPPX_CudaPitchedMemory* memory, void* destination, size_t destination_pitch, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_device_to_device(JYPPX_CudaPitchedMemory* destination, JYPPX_CudaPitchedMemory* source, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_host_to_device_async(JYPPX_CudaPitchedMemory* memory, const void* source, size_t source_pitch, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_device_to_host_async(JYPPX_CudaPitchedMemory* memory, void* destination, size_t destination_pitch, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memcpy_3d_device_to_device_async(JYPPX_CudaPitchedMemory* destination, JYPPX_CudaPitchedMemory* source, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memset_2d(JYPPX_CudaPitchedMemory* memory, int32_t value, size_t width_bytes, size_t height);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memset_2d_async(JYPPX_CudaPitchedMemory* memory, int32_t value, size_t width_bytes, size_t height, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memset_3d(JYPPX_CudaPitchedMemory* memory, int32_t value, size_t width_bytes, size_t height, size_t depth);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_memset_3d_async(JYPPX_CudaPitchedMemory* memory, int32_t value, size_t width_bytes, size_t height, size_t depth, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_free_pitch(JYPPX_CudaPitchedMemory* memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_host_alloc(size_t size, JYPPX_CudaPinnedMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_host_alloc_with_flags(size_t size, uint32_t flags, JYPPX_CudaPinnedMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_host_register(void* pointer, size_t size, uint32_t flags, JYPPX_CudaPinnedMemory** out_memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_host_get_size(JYPPX_CudaPinnedMemory* memory, size_t* out_size);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_host_get_flags(JYPPX_CudaPinnedMemory* memory, uint32_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_host_get_pointer(JYPPX_CudaPinnedMemory* memory, void** out_pointer);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_host_get_device_pointer(JYPPX_CudaPinnedMemory* memory, void** out_pointer);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_free_host(JYPPX_CudaPinnedMemory* memory);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_create_v2(uint32_t flags, JYPPX_CudaStream** out_stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_create_with_priority_v2(uint32_t flags, int32_t priority, JYPPX_CudaStream** out_stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_priority_range_v2(int32_t* out_least_priority, int32_t* out_greatest_priority);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_flags_v2(JYPPX_CudaStream* stream, uint32_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_priority_v2(JYPPX_CudaStream* stream, int32_t* out_priority);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_device_v2(JYPPX_CudaStream* stream, int32_t* out_device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_id_v2(JYPPX_CudaStream* stream, uint64_t* out_stream_id);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_query_v2(JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_synchronize_v2(JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_wait_event_v2(JYPPX_CudaStream* stream, JYPPX_CudaEvent* event_handle, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_begin_capture_v2(JYPPX_CudaStream* stream, int32_t mode);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_end_capture_v2(JYPPX_CudaStream* stream, JYPPX_CudaGraph** out_graph);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_get_capture_info_v2(JYPPX_CudaStream* stream, int32_t* out_capture_status, uint64_t* out_capture_id);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_is_capturing_v2(JYPPX_CudaStream* stream, int32_t* out_capture_status);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_copy_attributes_v2(JYPPX_CudaStream* destination, JYPPX_CudaStream* source);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_stream_destroy_v2(JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_create_v2(uint32_t flags, JYPPX_CudaEvent** out_event);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_create_with_flags_v2(uint32_t flags, JYPPX_CudaEvent** out_event);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_record_v2(JYPPX_CudaEvent* event_handle, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_record_with_flags_v2(JYPPX_CudaEvent* event_handle, JYPPX_CudaStream* stream, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_synchronize_v2(JYPPX_CudaEvent* event_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_query_v2(JYPPX_CudaEvent* event_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_get_flags_v2(JYPPX_CudaEvent* event_handle, uint32_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_elapsed_time_official(JYPPX_CudaEvent* start_event, JYPPX_CudaEvent* end_event, float* out_milliseconds);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_event_destroy_v2(JYPPX_CudaEvent* event_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_create_v2(uint32_t flags, JYPPX_CudaGraph** out_graph);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_clone_v2(JYPPX_CudaGraph* graph, JYPPX_CudaGraph** out_clone);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_node_count_v2(JYPPX_CudaGraph* graph, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_root_node_count_v2(JYPPX_CudaGraph* graph, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_edge_count_v2(JYPPX_CudaGraph* graph, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_instantiate_v2(JYPPX_CudaGraph* graph, uint64_t flags, JYPPX_CudaGraphExec** out_graph_exec);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_launch_v2(JYPPX_CudaGraphExec* graph_exec, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_upload_v2(JYPPX_CudaGraphExec* graph_exec, JYPPX_CudaStream* stream);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_get_flags_v2(JYPPX_CudaGraphExec* graph_exec, uint64_t* out_flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_destroy_v2(JYPPX_CudaGraphExec* graph_exec);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_destroy_v2(JYPPX_CudaGraph* graph);
/* END CUDA TWENTY-FOURTH BATCH GENERATED DECLARATIONS */

/* BEGIN CUDA TWENTY-FIFTH BATCH GRAPH TOPOLOGY DECLARATIONS */
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_empty_node_safe(JYPPX_CudaGraph* graph, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_empty_node_after_safe(JYPPX_CudaGraph* graph, uintptr_t dependency_node, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_dependency_safe(JYPPX_CudaGraph* graph, uintptr_t from_node, uintptr_t to_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_dependency_v2_safe(JYPPX_CudaGraph* graph, uintptr_t from_node, uintptr_t to_node, const JYPPX_CudaGraphEdgeData* edge_data);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_remove_dependency_safe(JYPPX_CudaGraph* graph, uintptr_t from_node, uintptr_t to_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_node_handle(JYPPX_CudaGraph* graph, size_t index, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_root_node_handle(JYPPX_CudaGraph* graph, size_t index, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_edge_handle_pair(JYPPX_CudaGraph* graph, size_t index, uintptr_t* out_from_node, uintptr_t* out_to_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_edges_v2_count_safe(JYPPX_CudaGraph* graph, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_edge_v2_safe(JYPPX_CudaGraph* graph, size_t index, uintptr_t* out_from_node, uintptr_t* out_to_node, JYPPX_CudaGraphEdgeData* out_edge_data);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_debug_dot_print_safe(JYPPX_CudaGraph* graph, const char* path, uint32_t flags);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_type_safe(uintptr_t node, int32_t* out_type);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_dependency_count_safe(uintptr_t node, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_dependency_safe(uintptr_t node, size_t index, uintptr_t* out_dependency_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_dependent_count_safe(uintptr_t node, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_dependent_safe(uintptr_t node, size_t index, uintptr_t* out_dependent_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_dependencies_v2_count_safe(uintptr_t node, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_dependency_v2_safe(uintptr_t node, size_t index, uintptr_t* out_dependency_node, JYPPX_CudaGraphEdgeData* out_edge_data);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_dependent_nodes_v2_count_safe(uintptr_t node, size_t* out_count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_dependent_node_v2_safe(uintptr_t node, size_t index, uintptr_t* out_dependent_node, JYPPX_CudaGraphEdgeData* out_edge_data);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_remove_dependency_v2_safe(JYPPX_CudaGraph* graph, uintptr_t from_node, uintptr_t to_node, const JYPPX_CudaGraphEdgeData* edge_data);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_find_in_clone_safe(uintptr_t original_node, JYPPX_CudaGraph* cloned_graph, uintptr_t* out_cloned_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_node_set_enabled_safe(JYPPX_CudaGraphExec* graph_exec, uintptr_t node, JYPPX_Boolean enabled);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_node_get_enabled_safe(JYPPX_CudaGraphExec* graph_exec, uintptr_t node, JYPPX_Boolean* out_enabled);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_get_id_safe(JYPPX_CudaGraph* graph, uint32_t* out_id);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_get_id_safe(JYPPX_CudaGraphExec* graph_exec, uint32_t* out_id);
/* END CUDA TWENTY-FIFTH BATCH GRAPH TOPOLOGY DECLARATIONS */

/* BEGIN CUDA FORTY-FOURTH BATCH GRAPH NODE PARAMETER DESCRIPTORS */
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memset_node_get_params_safe(uintptr_t node, JYPPX_CudaGraphMemsetNodeParams* out_params);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memset_node_set_params_safe(uintptr_t node, JYPPX_CudaMemory* destination, uint32_t value, size_t count);
/* END CUDA FORTY-FOURTH BATCH GRAPH NODE PARAMETER DESCRIPTORS */

/* BEGIN CUDA FORTY-SIXTH BATCH GRAPH EVENT NODES */
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_event_record_node_safe(JYPPX_CudaGraph* graph, uintptr_t dependency_node, JYPPX_CudaEvent* event_handle, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_event_wait_node_safe(JYPPX_CudaGraph* graph, uintptr_t dependency_node, JYPPX_CudaEvent* event_handle, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_event_record_node_set_event_safe(uintptr_t node, JYPPX_CudaEvent* event_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_event_record_node_has_event_safe(uintptr_t node, JYPPX_Boolean* out_has_event);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_event_wait_node_set_event_safe(uintptr_t node, JYPPX_CudaEvent* event_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_event_wait_node_has_event_safe(uintptr_t node, JYPPX_Boolean* out_has_event);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_event_record_node_set_event_safe(JYPPX_CudaGraphExec* graph_exec, uintptr_t node, JYPPX_CudaEvent* event_handle);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_event_wait_node_set_event_safe(JYPPX_CudaGraphExec* graph_exec, uintptr_t node, JYPPX_CudaEvent* event_handle);
/* END CUDA FORTY-SIXTH BATCH GRAPH EVENT NODES */

/* BEGIN CUDA FORTY-SEVENTH BATCH GRAPH MEMCPY 1D NODES */
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_memcpy_node_1d_device_to_device_safe(JYPPX_CudaGraph* graph, uintptr_t dependency_node, JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t count, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_memcpy_node_1d_host_to_device_safe(JYPPX_CudaGraph* graph, uintptr_t dependency_node, JYPPX_CudaMemory* destination, JYPPX_CudaPinnedMemory* source, size_t count, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_add_memcpy_node_1d_device_to_host_safe(JYPPX_CudaGraph* graph, uintptr_t dependency_node, JYPPX_CudaPinnedMemory* destination, JYPPX_CudaMemory* source, size_t count, uintptr_t* out_node);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memcpy_node_get_params_safe(uintptr_t node, JYPPX_CudaGraphMemcpyNodeParams* out_params);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memcpy_node_set_params_1d_device_to_device_safe(uintptr_t node, JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memcpy_node_set_params_1d_host_to_device_safe(uintptr_t node, JYPPX_CudaMemory* destination, JYPPX_CudaPinnedMemory* source, size_t count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memcpy_node_set_params_1d_device_to_host_safe(uintptr_t node, JYPPX_CudaPinnedMemory* destination, JYPPX_CudaMemory* source, size_t count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_memcpy_node_set_params_1d_device_to_device_safe(JYPPX_CudaGraphExec* graph_exec, uintptr_t node, JYPPX_CudaMemory* destination, JYPPX_CudaMemory* source, size_t count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_memcpy_node_set_params_1d_host_to_device_safe(JYPPX_CudaGraphExec* graph_exec, uintptr_t node, JYPPX_CudaMemory* destination, JYPPX_CudaPinnedMemory* source, size_t count);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_exec_memcpy_node_set_params_1d_device_to_host_safe(JYPPX_CudaGraphExec* graph_exec, uintptr_t node, JYPPX_CudaPinnedMemory* destination, JYPPX_CudaMemory* source, size_t count);
/* END CUDA FORTY-SEVENTH BATCH GRAPH MEMCPY 1D NODES */

/* BEGIN CUDA FORTY-EIGHTH BATCH GRAPH KERNEL NODE ATTRIBUTES */
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_kernel_node_get_attribute_scalar_safe(uintptr_t node, int32_t attribute, JYPPX_CudaGraphKernelNodeAttributeValue* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_kernel_node_set_attribute_scalar_safe(uintptr_t node, const JYPPX_CudaGraphKernelNodeAttributeValue* value);
/* END CUDA FORTY-EIGHTH BATCH GRAPH KERNEL NODE ATTRIBUTES */

/* BEGIN CUDA TWENTY-NINTH BATCH GRAPH MEMORY AND NODE IDENTITY DECLARATIONS */
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_graph_memory_attribute(int32_t device, int32_t attribute, uint64_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_trim_graph_memory(int32_t device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_reset_graph_memory_high_watermark(int32_t device, int32_t attribute);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_graph_memory_used_current(int32_t device, uint64_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_graph_memory_used_high(int32_t device, uint64_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_graph_memory_reserved_current(int32_t device, uint64_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_get_graph_memory_reserved_high(int32_t device, uint64_t* out_value);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_reset_graph_memory_used_high(int32_t device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_device_reset_graph_memory_reserved_high(int32_t device);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_is_in_graph_safe(JYPPX_CudaGraph* graph, uintptr_t node, JYPPX_Boolean* out_is_in_graph);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_local_id_safe(uintptr_t node, uint32_t* out_node_id);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_tools_id_safe(uintptr_t node, uint64_t* out_tools_node_id);
/* END CUDA TWENTY-NINTH BATCH GRAPH MEMORY AND NODE IDENTITY DECLARATIONS */

/* BEGIN CUDA THIRTY-SEVENTH BATCH GRAPH BOUNDARY DECLARATIONS */
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_kernel_node_get_attribute_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_kernel_node_get_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_kernel_node_set_attribute_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_kernel_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_mem_alloc_node_get_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memcpy_node_get_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memcpy_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memcpy_node_set_params_1d_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memcpy_node_set_params_from_symbol_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memcpy_node_set_params_to_symbol_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_mem_free_node_get_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memset_node_get_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_memset_node_set_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_containing_graph_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_dependencies_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_dependent_nodes_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_node_get_params_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_remove_dependencies_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_retain_user_object_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_graph_release_user_object_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_user_object_create_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_user_object_retain_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_user_object_release_deferred(void);
/* END CUDA THIRTY-SEVENTH BATCH GRAPH BOUNDARY DECLARATIONS */

/* BEGIN CUDA THIRTY-EIGHTH BATCH OTHER BOUNDARY DECLARATIONS */
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_create_surface_object_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_create_texture_object_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_create_texture_object_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_destroy_surface_object_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_destroy_texture_object_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_surface_object_resource_desc_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_texture_object_resource_desc_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_texture_object_resource_view_desc_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_texture_object_texture_desc_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_texture_object_texture_desc_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_destroy_external_memory_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_destroy_external_semaphore_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_external_memory_get_mapped_buffer_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_external_memory_get_mapped_mipmapped_array_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_import_external_memory_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_import_external_semaphore_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_signal_external_semaphores_async_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_signal_external_semaphores_async_ptsz_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_signal_external_semaphores_async_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_wait_external_semaphores_async_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_wait_external_semaphores_async_ptsz_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_wait_external_semaphores_async_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_ipc_close_mem_handle_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_ipc_get_event_handle_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_ipc_get_mem_handle_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_ipc_open_event_handle_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_ipc_open_mem_handle_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_driver_entry_point_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_driver_entry_point_by_version_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_export_table_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_func_by_symbol_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_kernel_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_symbol_address_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_get_symbol_size_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_kernel_set_attribute_for_device_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_library_enumerate_kernels_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_library_get_global_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_library_get_kernel_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_library_get_kernel_count_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_library_get_managed_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_library_get_unified_function_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_library_load_data_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_library_load_from_file_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_library_unload_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_dev_resource_generate_desc_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_dev_sm_resource_split_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_dev_sm_resource_split_by_count_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_execution_ctx_destroy_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_execution_ctx_get_device_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_execution_ctx_get_dev_resource_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_execution_ctx_get_id_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_execution_ctx_record_event_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_execution_ctx_stream_create_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_execution_ctx_synchronize_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_execution_ctx_wait_event_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_green_ctx_create_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_logs_current_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_logs_dump_to_file_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_logs_dump_to_memory_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_logs_register_callback_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_logs_unregister_callback_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_advise_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_discard_and_prefetch_batch_async_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_discard_batch_async_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_prefetch_async_v2_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_prefetch_batch_async_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_range_get_attribute_deferred(void);
JYPPX_C_API(JYPPX_StatusCode) jyppx_cuda_mem_range_get_attributes_deferred(void);
/* END CUDA THIRTY-EIGHTH BATCH OTHER BOUNDARY DECLARATIONS */
