<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22</PackageId>
    <Title>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22</Title>
    <Description>Split runtime collection package for TensorRT 10.11.0.33 + CUDA 12.9 + cuDNN 9.22.0 on win-x64.</Description>
    <JYPPXRuntimeKey>win-x64-trt10.11-cuda12.9-cudnn9.22-meta</JYPPXRuntimeKey>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    <PackageTags>TensorRT;CUDA;cuDNN;runtime;split-delivery;collection;meta</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22.Bridge" Version="$(JYPPXBridgePackageVersion)" />
    <PackageReference Include="JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22.Vendor" Version="$(JYPPXVendorPackageVersion)" />
  </ItemGroup>
</Project>
