<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22.Vendor</PackageId>
    <Title>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22.Vendor</Title>
    <Description>Vendor NVIDIA runtime libraries for TensorRT 10.11.0.33, CUDA 12.9, and cuDNN 9.22.0 on win-x64.</Description>
    <JYPPXRuntimeKey>win-x64-trt10.11-cuda12.9-cudnn9.22-vendor</JYPPXRuntimeKey>
    <PackageTags>TensorRT;CUDA;cuDNN;runtime;split-delivery;vendor</PackageTags>
  </PropertyGroup>
</Project>
