<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>JYPPX.TensorRT.CSharp.API.Runtime.linux-x64.trt10.11.cuda12.9.cudnn9.22</PackageId>
    <Title>JYPPX.TensorRT.CSharp.API.Runtime.linux-x64.trt10.11.cuda12.9.cudnn9.22</Title>
    <JYPPXRuntimeKey>linux-x64-trt10.11-cuda12.9-cudnn9.22</JYPPXRuntimeKey>
  </PropertyGroup>
</Project>
