using System;
using System.Runtime.InteropServices;
using JYPPX.Shared;
using JYPPX.Shared.Interop;
{{ExtraUsings}}

namespace {{Namespace}};

/// <summary>
/// Generated module-specific interop declarations.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// </summary>
internal static partial class {{ClassName}}
{
{{NativeMethodRows}}
}
