using System;
using System.Runtime.InteropServices;
using JYPPX.Shared.Interop;

namespace JYPPX.Shared.Generated;

/// <summary>
/// Generated bridge interop declarations.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// </summary>
internal static partial class GeneratedNativeMethods
{
{{NativeMethodRows}}
}
