namespace JYPPX.TensorRtSharp.Shared.Generated;

/// <summary>
/// Generated bridge entry point names.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// 生成的 bridge 入口点名称；由 JYPPX.BindingGenerator 在 {{GeneratedOn}} 生成。
/// </summary>
internal static class GeneratedEntryPointNames
{
{{EntryPointRows}}
}
