using JYPPX.Shared.Interop;
using JYPPX.TensorRtSharp.Internal.Handles;

namespace JYPPX.TensorRtSharp.Internal.Interop;

/// <summary>
/// Generated TensorRT line helper methods.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// 生成的 TensorRT line helper 方法；由 JYPPX.BindingGenerator 在 {{GeneratedOn}} 生成。
/// </summary>
internal static partial class NativeBridgeApi
{
{{HelperRows}}
}
