using System;
using JYPPX.CudaSharp.Internal.Handles;
using JYPPX.Shared.Interop;

namespace JYPPX.CudaSharp.Internal.Interop;

/// <summary>
/// Generated thin CUDA wrapper methods.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// </summary>
internal static partial class NativeCudaApi
{
{{DescriptorRows}}
{{MethodRows}}
}
