using System;
using System.Text;
using JYPPX.TensorRtSharp.Shared.Interop;

namespace {{Namespace}};

/// <summary>
/// Generated common bridge helpers.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// 生成的 common bridge helper；由 JYPPX.BindingGenerator 在 {{GeneratedOn}} 生成。
/// </summary>
internal static partial class NativeBridgeApi
{
{{MethodRows}}
}
