using System;
using System.Text;
using JYPPX.Shared.Interop;

namespace {{Namespace}};

/// <summary>
/// Generated common bridge helpers.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// </summary>
internal static partial class NativeBridgeApi
{
{{MethodRows}}
}
