namespace JYPPX.Shared.Generated;

/// <summary>
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// </summary>
public static partial class GeneratedApiCatalog
{
    public static readonly GeneratedApiDefinition[] Definitions =
    {
{{ApiRows}}
    };
}

