using System;
using System.Runtime.InteropServices;
using JYPPX.TensorRtSharp.Shared;
using JYPPX.TensorRtSharp.Shared.Interop;
{{ExtraUsings}}

namespace {{Namespace}};

/// <summary>
/// Generated module-specific interop declarations.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// 生成的模块专用 interop 声明；由 JYPPX.BindingGenerator 在 {{GeneratedOn}} 生成。
/// </summary>
internal static partial class {{ClassName}}
{
{{NativeMethodRows}}
}
