namespace JYPPX.Shared.Generated;

/// <summary>
/// Generated bridge entry point names.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// </summary>
internal static class GeneratedEntryPointNames
{
{{EntryPointRows}}
}
