using JYPPX.Shared.Interop;
using JYPPX.TensorRtSharp.Internal.Handles;

namespace JYPPX.TensorRtSharp.Internal.Interop;

/// <summary>
/// Generated TensorRT line binding descriptors.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// 生成的 TensorRT line 绑定描述；由 JYPPX.BindingGenerator 在 {{GeneratedOn}} 生成。
/// </summary>
internal static partial class NativeBridgeApi
{
{{BindingRows}}
}
