using JYPPX.Shared.Interop;
using JYPPX.TensorRtSharp.Internal.Handles;

namespace JYPPX.TensorRtSharp.Internal.Interop;

/// <summary>
/// Generated TensorRT line binding descriptors.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// </summary>
internal static partial class NativeBridgeApi
{
{{BindingRows}}
}
