using System;
using System.Runtime.InteropServices;
using JYPPX.Shared.Interop;

namespace JYPPX.Shared.Generated;

/// <summary>
/// Generated bridge interop declarations.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// 生成的 bridge interop 声明；由 JYPPX.BindingGenerator 在 {{GeneratedOn}} 生成。
/// </summary>
internal static partial class GeneratedNativeMethods
{
{{NativeMethodRows}}
}
