namespace JYPPX.Shared.Generated;

/// <summary>
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// 由 JYPPX.BindingGenerator 在 {{GeneratedOn}} 生成。
/// </summary>
internal static partial class GeneratedApiCatalog
{
    internal static readonly GeneratedApiDefinition[] Definitions =
    {
{{ApiRows}}
    };
}
