using System;
using JYPPX.CudaSharp.Internal.Handles;
using JYPPX.Shared.Interop;

namespace JYPPX.CudaSharp.Internal.Interop;

/// <summary>
/// Generated thin CUDA wrapper methods.
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// 生成的轻量 CUDA wrapper 方法；由 JYPPX.BindingGenerator 在 {{GeneratedOn}} 生成。
/// </summary>
internal static partial class NativeCudaApi
{
{{DescriptorRows}}
{{MethodRows}}
}
