namespace JYPPX.Shared.Generated;

/// <summary>
/// Generated by JYPPX.BindingGenerator on {{GeneratedOn}}.
/// </summary>
internal static partial class GeneratedApiCatalog
{
    internal static readonly GeneratedApiDefinition[] Definitions =
    {
{{ApiRows}}
    };
}
