<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda11.8.cudnn8.9.Extensions</PackageId>
    <Title>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda11.8.cudnn8.9.Extensions</Title>
    <JYPPXRuntimeKey>win-x64-trt10.11-cuda11.8-cudnn8.9-extensions</JYPPXRuntimeKey>
    <PackageTags>TensorRT;CUDA;runtime;split-delivery;extensions;prototype</PackageTags>
  </PropertyGroup>
</Project>
