<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22.TensorRtExtensions</PackageId>
    <Title>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22.TensorRtExtensions</Title>
    <JYPPXRuntimeKey>win-x64-trt10.11-cuda12.9-cudnn9.22-tensorrt-extensions</JYPPXRuntimeKey>
    <PackageTags>TensorRT;CUDA;runtime;split-delivery;tensorrt;extensions</PackageTags>
  </PropertyGroup>
</Project>
