<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt11.0.cuda12.9.cudnn9.22.TensorRtBuilder.Sm75Sm86</PackageId>
    <Title>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt11.0.cuda12.9.cudnn9.22.TensorRtBuilder.Sm75Sm86</Title>
    <JYPPXRuntimeKey>win-x64-trt11.0-cuda12.9-cudnn9.22-tensorrt-builder-sm75-sm86</JYPPXRuntimeKey>
    <PackageTags>TensorRT;CUDA;runtime;split-delivery;builder;sm75;sm80;sm86</PackageTags>
  </PropertyGroup>
</Project>
