[CmdletBinding()]
param(
  [string]$RepositoryRoot
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) {
  if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) {
    $scriptRoot = (Get-Location).Path
  }
  else {
    $scriptRoot = $PSScriptRoot
  }

  $RepositoryRoot = (Resolve-Path (Join-Path $scriptRoot "..")).Path
}

$utf8 = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = $utf8
$OutputEncoding = $utf8

function Test-File {
  param(
    [string]$Path
  )

  return Test-Path -LiteralPath (Join-Path $RepositoryRoot $Path) -PathType Leaf
}

function Test-AnyFile {
  param(
    [string]$Directory,
    [string]$Filter
  )

  return @(Get-ChildItem -LiteralPath (Join-Path $RepositoryRoot $Directory) -Filter $Filter -ErrorAction SilentlyContinue).Count -gt 0
}

function Test-Directory {
  param(
    [string]$Path
  )

  return Test-Path -LiteralPath (Join-Path $RepositoryRoot $Path) -PathType Container
}

function Read-JsonOrNull {
  param(
    [string]$Path
  )

  $fullPath = Join-Path $RepositoryRoot $Path
  if (-not (Test-Path -LiteralPath $fullPath -PathType Leaf)) {
    return $null
  }

  return Get-Content -LiteralPath $fullPath -Raw -Encoding utf8 | ConvertFrom-Json
}

function Get-PropertyOrDefault {
  param(
    [AllowNull()][object]$Object,
    [string]$Name,
    [AllowNull()][object]$DefaultValue
  )

  if ($null -eq $Object) {
    return $DefaultValue
  }

  if ($Object.PSObject.Properties.Name -contains $Name) {
    return $Object.PSObject.Properties[$Name].Value
  }

  return $DefaultValue
}

function New-ChecklistItem {
  param(
    [string]$Category,
    [string]$Name,
    [bool]$Ready,
    [string]$Evidence,
    [string]$Notes
  )

  return [pscustomobject]@{
    category = $Category
    name = $Name
    ready = $Ready
    evidence = $Evidence
    notes = $Notes
  }
}

$items = New-Object System.Collections.Generic.List[object]

$runtimeReadiness = Read-JsonOrNull "artifacts\package-readiness\runtime-package-readiness-summary.json"
$packageConsumer = Read-JsonOrNull "artifacts\package-consumer\package-consumer-validation-summary.json"
$bridgeConsumer = Read-JsonOrNull "artifacts\package-consumer\bridge-package-consumer-validation-summary.json"
$compatibleBridgeRuntimeProofPath = "artifacts\package-consumer\bridge-runtime\win-x64-trt10.11-cuda12.9-cudnn9.22\bridge-package-runtime-consumer-proof.json"
$compatibleBridgeRuntimeProof = Read-JsonOrNull $compatibleBridgeRuntimeProofPath
$localFeedConsumer = Read-JsonOrNull "artifacts\local-feed-consumer\local-nuget-feed-consumer-summary.json"
$releaseReadiness = Read-JsonOrNull "artifacts\release-candidate\release-candidate-readiness-summary.json"
$bilingualDocumentationAudit = Read-JsonOrNull "artifacts\api-doc-audit\public-api-bilingual-documentation-audit.json"
$bilingualDocumentationBacklog = Read-JsonOrNull "artifacts\api-doc-audit\public-api-bilingual-documentation-backlog.json"
$compatibleHostRuntimeProofCollectionBundle = Read-JsonOrNull "artifacts\final-release\compatible-host-runtime-proof-collection-bundle.json"

if ($bilingualDocumentationAudit) {
  $bilingualDocumentationFindingCount = [int]$bilingualDocumentationAudit.findingCount
  $bilingualDocumentationNotes = "Generated by Test-PublicApiBilingualDocumentation.ps1; findingCount=$bilingualDocumentationFindingCount."
}
else {
  $bilingualDocumentationFindingCount = -1
  $bilingualDocumentationNotes = "Generated by Test-PublicApiBilingualDocumentation.ps1; report is missing."
}
$compatibleHostRuntimeProofCollectionBundleCommands = Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "commands" -DefaultValue $null
$compatibleHostRuntimeProofCollectionBundleOperatorQuickStart = @(Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "operatorQuickStart" -DefaultValue @())
$compatibleHostRuntimeProofCollectionBundlePreflightChecklist = @(Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "preflightChecklist" -DefaultValue @())
$compatibleHostRuntimeProofCollectionBundleCopyableExecutionOrder = @(Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "copyableExecutionOrder" -DefaultValue @())
$compatibleHostRuntimeProofCollectionBundleStateFallback = [string](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "compatibleHostRuntimeProofCollectionBundleState" -DefaultValue "missing-compatible-host-runtime-proof-collection-bundle")
$compatibleHostRuntimeProofCollectionBundleStateFallback = [string](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "state" -DefaultValue $compatibleHostRuntimeProofCollectionBundleStateFallback)
$compatibleHostRuntimeProofCollectionBundleState = [string](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "collectionState" -DefaultValue $compatibleHostRuntimeProofCollectionBundleStateFallback)
$compatibleHostRuntimeProofCollectionBundlePerformsPublish = [bool](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "performsPublish" -DefaultValue ([bool](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "compatibleHostRuntimeProofCollectionBundlePerformsPublish" -DefaultValue $false)))
$compatibleHostRuntimeProofCollectionBundleApprovesPublicRelease = [bool](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "approvesPublicRelease" -DefaultValue ([bool](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "compatibleHostRuntimeProofCollectionBundleApprovesPublicRelease" -DefaultValue $false)))
$compatibleHostRuntimeProofCollectionBundleCanPromoteRuntimeProof = [bool](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "canPromoteRuntimeProof" -DefaultValue ([bool](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "compatibleHostRuntimeProofCollectionBundleCanPromoteRuntimeProof" -DefaultValue $false)))
$compatibleHostRuntimeProofCollectionBundleRuntimeExecutionEvidence = [bool](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "isRuntimeExecutionEvidence" -DefaultValue ([bool](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "compatibleHostRuntimeProofCollectionBundleRuntimeExecutionEvidence" -DefaultValue $false)))
$compatibleHostRuntimeProofCollectionBundleRunPackageConsumerSmokeCommandFallback = [string](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "compatibleHostRuntimeProofCollectionBundleRunPackageConsumerSmokeCommand" -DefaultValue "pwsh -NoProfile -ExecutionPolicy Bypass -File .\eng\Test-PackageConsumer.ps1 -RunSmoke -RequirePackageReference")
$compatibleHostRuntimeProofCollectionBundleRunPackageConsumerSmokeCommandFallback = [string](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "runPackageConsumerSmokeCommand" -DefaultValue $compatibleHostRuntimeProofCollectionBundleRunPackageConsumerSmokeCommandFallback)
$compatibleHostRuntimeProofCollectionBundleRunPackageConsumerSmokeCommand = [string](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundleCommands -Name "runPackageConsumerSmoke" -DefaultValue $compatibleHostRuntimeProofCollectionBundleRunPackageConsumerSmokeCommandFallback)
$compatibleHostRuntimeProofCollectionBundleValidateFilledRecordCommandFallback = [string](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "compatibleHostRuntimeProofCollectionBundleValidateFilledRecordCommand" -DefaultValue "pwsh -NoProfile -ExecutionPolicy Bypass -File .\eng\Test-ExternalRuntimeProofRecord.ps1 -InputPath artifacts/final-release/external-runtime-proof-record.json -RequireExistingLog -FailOnNotProof")
$compatibleHostRuntimeProofCollectionBundleValidateFilledRecordCommandFallback = [string](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundle -Name "validateFilledRecordCommand" -DefaultValue $compatibleHostRuntimeProofCollectionBundleValidateFilledRecordCommandFallback)
$compatibleHostRuntimeProofCollectionBundleValidateFilledRecordCommand = [string](Get-PropertyOrDefault -Object $compatibleHostRuntimeProofCollectionBundleCommands -Name "validateFilledRecord" -DefaultValue $compatibleHostRuntimeProofCollectionBundleValidateFilledRecordCommandFallback)
$compatibleHostRuntimeProofCollectionBundleQuickStartCount = $compatibleHostRuntimeProofCollectionBundleOperatorQuickStart.Count
$compatibleHostRuntimeProofCollectionBundlePreflightCount = $compatibleHostRuntimeProofCollectionBundlePreflightChecklist.Count
$compatibleHostRuntimeProofCollectionBundleExecutionOrderCount = $compatibleHostRuntimeProofCollectionBundleCopyableExecutionOrder.Count
$compatibleHostRuntimeProofCollectionBundleFirstExecutionCommand = if ($compatibleHostRuntimeProofCollectionBundleExecutionOrderCount -gt 0) { [string]$compatibleHostRuntimeProofCollectionBundleCopyableExecutionOrder[0] } else { "missing-copyable-execution-order" }
$compatibleHostRuntimeProofCollectionBundleLastExecutionCommand = if ($compatibleHostRuntimeProofCollectionBundleExecutionOrderCount -gt 0) { [string]$compatibleHostRuntimeProofCollectionBundleCopyableExecutionOrder[$compatibleHostRuntimeProofCollectionBundleExecutionOrderCount - 1] } else { "missing-copyable-execution-order" }
$compatibleHostRuntimeProofCollectionBundleReady = $compatibleHostRuntimeProofCollectionBundle -and
  -not $compatibleHostRuntimeProofCollectionBundlePerformsPublish -and
  -not $compatibleHostRuntimeProofCollectionBundleApprovesPublicRelease -and
  -not $compatibleHostRuntimeProofCollectionBundleCanPromoteRuntimeProof -and
  -not $compatibleHostRuntimeProofCollectionBundleRuntimeExecutionEvidence -and
  $compatibleHostRuntimeProofCollectionBundleQuickStartCount -ge 5 -and
  $compatibleHostRuntimeProofCollectionBundlePreflightCount -ge 5 -and
  $compatibleHostRuntimeProofCollectionBundleExecutionOrderCount -ge 8
$compatibleBridgeRuntimeProofHashesReady = $compatibleBridgeRuntimeProof -and
  [string]$compatibleBridgeRuntimeProof.packages.managed.sha256 -match '^[A-Fa-f0-9]{64}$' -and
  [string]$compatibleBridgeRuntimeProof.packages.bridge.sha256 -match '^[A-Fa-f0-9]{64}$' -and
  [string]$compatibleBridgeRuntimeProof.logs.stdoutSha256 -match '^[A-Fa-f0-9]{64}$' -and
  [string]$compatibleBridgeRuntimeProof.logs.stderrSha256 -match '^[A-Fa-f0-9]{64}$' -and
  [string]$compatibleBridgeRuntimeProof.logs.combinedSha256 -match '^[A-Fa-f0-9]{64}$'
$compatibleBridgeRuntimeProofReady = $compatibleBridgeRuntimeProof -and
  [string]$compatibleBridgeRuntimeProof.proofClassification -eq "compatible-host-bridge-package-runtime" -and
  [string]$compatibleBridgeRuntimeProof.smokeStatus -eq "passed" -and
  [int]$compatibleBridgeRuntimeProof.exitCode -eq 0 -and
  [bool]$compatibleBridgeRuntimeProof.isRuntimeExecutionProof -and
  -not [bool]$compatibleBridgeRuntimeProof.isPackageConsumerRuntimeProof -and
  [bool]$compatibleBridgeRuntimeProof.canPromoteCompatibleHostRuntimeProof -and
  -not [bool]$compatibleBridgeRuntimeProof.canPublishPublicly -and
  -not [bool]$compatibleBridgeRuntimeProof.canCloseReleaseIssue -and
  [bool]$compatibleBridgeRuntimeProof.consumerRootOutsideRepository -and
  -not [bool]$compatibleBridgeRuntimeProof.consumer.usesProjectReference -and
  $compatibleBridgeRuntimeProofHashesReady

$items.Add((New-ChecklistItem -Category "managed" -Name "Managed package artifact" -Ready (Test-AnyFile "artifacts\managed" "JYPPX.TensorRT.CSharp.API.*.nupkg") -Evidence "artifacts/managed/JYPPX.TensorRT.CSharp.API.*.nupkg" -Notes "Generated by dotnet pack."))
$items.Add((New-ChecklistItem -Category "runtime" -Name "Runtime package readiness summary" -Ready ($runtimeReadiness -and $runtimeReadiness.overallStatus -in @("ready", "ready-with-warnings")) -Evidence "artifacts/package-readiness/runtime-package-readiness-summary.json" -Notes "Aggregates managed package, split runtime packages, native dependency probes, wrapper surface, and callback proof boundaries."))
$items.Add((New-ChecklistItem -Category "consumer" -Name "Bridge package consumer validation" -Ready ($bridgeConsumer -and $bridgeConsumer.NativeDependencyStatus -eq "ready") -Evidence "artifacts/package-consumer/bridge-package-consumer-validation-summary.json" -Notes "Validates bridge split package consumption without treating it as full runtime callback proof."))
$items.Add((New-ChecklistItem -Category "runtime-proof" -Name "TRT10 compatible bridge package runtime proof" -Ready $compatibleBridgeRuntimeProofReady -Evidence $compatibleBridgeRuntimeProofPath.Replace('\', '/') -Notes "Executes build/serialize/deserialize/enqueue/output-compare from an external PackageReference consumer with system TensorRT/CUDA dependencies. It is runtime execution proof for this compatible host, but isPackageConsumerRuntimeProof=false, canPublishPublicly=false, and canCloseReleaseIssue=false."))
$items.Add((New-ChecklistItem -Category "consumer" -Name "Full package consumer native asset validation" -Ready ($packageConsumer -and $packageConsumer.NativeAssetsFound -eq $packageConsumer.NativeAssetsExpected) -Evidence "artifacts/package-consumer/package-consumer-validation-summary.json" -Notes "Validates managed/runtime package restore, build, and native asset copy. Runtime smoke may remain environment-blocked."))
$items.Add((New-ChecklistItem -Category "consumer" -Name "Local NuGet feed consumer validation" -Ready ($localFeedConsumer -and -not [bool]$localFeedConsumer.UsesProjectReference -and $localFeedConsumer.NativeAssetsFound -eq $localFeedConsumer.NativeAssetsExpected) -Evidence "artifacts/local-feed-consumer/local-nuget-feed-consumer-summary.json" -Notes "Validates a source-free PackageReference consumer from a local feed."))
$items.Add((New-ChecklistItem -Category "release-candidate" -Name "Aggregated release candidate readiness" -Ready ($releaseReadiness -and [int]$releaseReadiness.blockingIssueCount -eq 0) -Evidence "artifacts/release-candidate/release-candidate-readiness-summary.json" -Notes "Zero blockers means package/readiness evidence is coherent. Warnings such as CUDA error 35, unsigned output, or callback proof=false must remain visible."))
$items.Add((New-ChecklistItem -Category "release-candidate" -Name "Runtime package matrix" -Ready (Test-File "artifacts\release-candidate\runtime-package-matrix.json") -Evidence "artifacts/release-candidate/runtime-package-matrix.json" -Notes "Cross-version matrix for Windows TRT8/TRT10/TRT11 and Linux Ubuntu runtime lines."))
$items.Add((New-ChecklistItem -Category "interop" -Name "Binding generator comparison report" -Ready (Test-File "artifacts\interop-comparison\native-methods-comparison.md") -Evidence "artifacts/interop-comparison/native-methods-comparison.md" -Notes "Generated by Test-BindingGeneratorOutputs.ps1 or Export-NativeMethodsComparison.ps1."))
$items.Add((New-ChecklistItem -Category "interop" -Name "Generated API coverage report" -Ready (Test-File "artifacts\interop-comparison\generated-api-coverage.md") -Evidence "artifacts/interop-comparison/generated-api-coverage.md" -Notes "Generated by Test-BindingGeneratorOutputs.ps1 or Export-GeneratedApiCoverage.ps1."))
$items.Add((New-ChecklistItem -Category "coverage" -Name "TensorRT interface coverage matrix" -Ready (Test-File "artifacts\interface-coverage\tensorrt-interface-comparison.csv") -Evidence "artifacts/interface-coverage/tensorrt-interface-comparison.csv" -Notes "Deferred rows are intentional boundary records and must not be deleted to manufacture completion."))
$items.Add((New-ChecklistItem -Category "coverage" -Name "Project completion review" -Ready (Test-File "artifacts\interface-coverage\project-completion-review.md") -Evidence "artifacts/interface-coverage/project-completion-review.md" -Notes "Completion is interpreted through non-deferred implementation, wrappers, consumer validation, and release evidence."))
$items.Add((New-ChecklistItem -Category "runtime" -Name "Runtime distribution report" -Ready (Test-File "artifacts\runtime-distribution\runtime-distribution-report.md") -Evidence "artifacts/runtime-distribution/runtime-distribution-report.md" -Notes "Generated by Export-RuntimeDistributionReport.ps1."))
$items.Add((New-ChecklistItem -Category "runtime" -Name "Runtime delivery strategy" -Ready (Test-File "artifacts\runtime-distribution\runtime-delivery-strategy.md") -Evidence "artifacts/runtime-distribution/runtime-delivery-strategy.md" -Notes "Generated by Export-RuntimeDeliveryStrategy.ps1."))
$items.Add((New-ChecklistItem -Category "runtime" -Name "Split runtime package report" -Ready (Test-File "artifacts\runtime-distribution\split-runtime-packages-report.md") -Evidence "artifacts/runtime-distribution/split-runtime-packages-report.md" -Notes "Generated by Validate-SplitRuntimePackages.ps1."))
$items.Add((New-ChecklistItem -Category "runtime" -Name "Release gate summary" -Ready (Test-File "artifacts\runtime-distribution\release-gate-summary.md") -Evidence "artifacts/runtime-distribution/release-gate-summary.md" -Notes "Generated by Export-ReleaseGateSummary.ps1."))
$items.Add((New-ChecklistItem -Category "consumer" -Name "Package consumer validation summary" -Ready (Test-File "artifacts\package-consumer\package-consumer-validation-summary.md") -Evidence "artifacts/package-consumer/package-consumer-validation-summary.md" -Notes "Generated by Test-PackageConsumer.ps1."))
$items.Add((New-ChecklistItem -Category "runtime-proof" -Name "Compatible host runtime proof collection bundle" -Ready $compatibleHostRuntimeProofCollectionBundleReady -Evidence "artifacts/final-release/compatible-host-runtime-proof-collection-bundle.json" -Notes "Collection bundle is executable guidance, not runtime proof or publish approval. State=$compatibleHostRuntimeProofCollectionBundleState; canPromoteRuntimeProof=$compatibleHostRuntimeProofCollectionBundleCanPromoteRuntimeProof; runtimeExecutionEvidence=$compatibleHostRuntimeProofCollectionBundleRuntimeExecutionEvidence; quickStart=$compatibleHostRuntimeProofCollectionBundleQuickStartCount; preflight=$compatibleHostRuntimeProofCollectionBundlePreflightCount; copyableExecutionOrder=$compatibleHostRuntimeProofCollectionBundleExecutionOrderCount. First command: $compatibleHostRuntimeProofCollectionBundleFirstExecutionCommand. Last command: $compatibleHostRuntimeProofCollectionBundleLastExecutionCommand. Run smoke: $compatibleHostRuntimeProofCollectionBundleRunPackageConsumerSmokeCommand. Validate filled external-runtime-proof-record.json: $compatibleHostRuntimeProofCollectionBundleValidateFilledRecordCommand."))
$items.Add((New-ChecklistItem -Category "docs" -Name "Public API bilingual documentation audit" -Ready ($bilingualDocumentationAudit -and $bilingualDocumentationFindingCount -eq 0) -Evidence "artifacts/api-doc-audit/public-api-bilingual-documentation-audit.md" -Notes $bilingualDocumentationNotes))
$items.Add((New-ChecklistItem -Category "docs" -Name "Public API bilingual documentation backlog" -Ready (($bilingualDocumentationFindingCount -eq 0) -or ($bilingualDocumentationBacklog -and [int]$bilingualDocumentationBacklog.backlogFindingCount -eq $bilingualDocumentationFindingCount)) -Evidence "artifacts/api-doc-audit/public-api-bilingual-documentation-backlog.md" -Notes "Generated by Export-PublicApiBilingualDocumentationBacklog.ps1 when bilingual findings remain; it is a work queue and does not make the audit ready."))
$items.Add((New-ChecklistItem -Category "docs" -Name "DocFX site output" -Ready (Test-File "docs\_site\index.html") -Evidence "docs/_site/index.html" -Notes "Generated by dotnet docfx docs/docfx.json."))
$items.Add((New-ChecklistItem -Category "linux" -Name "Linux handoff and validation artifacts" -Ready (Test-Directory "artifacts\linux-dry-run") -Evidence "artifacts/linux-dry-run" -Notes "Linux artifacts are handoff/dry-run evidence until a matching Linux x64 runner produces build, pack, runtime asset collection, and package consumer proof. Future ARM/Jetson/non-Ubuntu lines require dedicated package identities and runners."))
$items.Add((New-ChecklistItem -Category "workflow" -Name "Workflow contract report" -Ready (Test-File "artifacts\workflow-contracts\workflow-contract-report.md") -Evidence "artifacts/workflow-contracts/workflow-contract-report.md" -Notes "Generated by Test-WorkflowContracts.ps1."))

$manifestPath = Join-Path $RepositoryRoot "pack\runtime\runtime-packages.manifest.json"
$manifest = Get-Content -LiteralPath $manifestPath -Raw -Encoding utf8 | ConvertFrom-Json
$localValidated = @($manifest.packages | Where-Object { $_.validationState -eq "local-validated" }).Count
$pendingLocalValidation = @($manifest.packages | Where-Object { $_.validationState -eq "pending-local-validation" }).Count
$dryRunOnly = @($manifest.packages | Where-Object { $_.validationState -eq "dry-run-only" }).Count
$knownValidationStates = @("local-validated", "pending-local-validation", "dry-run-only")
$unknownValidationStates = @(
  $manifest.packages |
    Where-Object { $knownValidationStates -notcontains $_.validationState } |
    Select-Object -ExpandProperty validationState -Unique
)
if ($unknownValidationStates.Count -gt 0) {
  $unknownStateNotes = " Unknown validation state(s): $($unknownValidationStates -join ', ')."
}
else {
  $unknownStateNotes = ""
}
$validationStateNotes = "$localValidated local-validated package(s), $pendingLocalValidation pending-local-validation package(s), $dryRunOnly dry-run-only package(s).$unknownStateNotes"
$items.Add((New-ChecklistItem -Category "runtime" -Name "Runtime validation state matrix" -Ready ($localValidated -ge 4 -and $dryRunOnly -ge 4 -and $unknownValidationStates.Count -eq 0) -Evidence "pack/runtime/runtime-packages.manifest.json" -Notes $validationStateNotes))

$outputRoot = Join-Path $RepositoryRoot "artifacts\release-candidate"
New-Item -ItemType Directory -Path $outputRoot -Force | Out-Null

$jsonPath = Join-Path $outputRoot "release-candidate-checklist.json"
$items | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $jsonPath -Encoding utf8

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Release Candidate Checklist")
$lines.Add("")
$lines.Add("Generated on: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
$lines.Add("")
$lines.Add("| Category | Check | Status | Evidence | Notes |")
$lines.Add("| --- | --- | --- | --- | --- |")
foreach ($item in $items) {
  if ($item.ready) {
    $status = "ready"
  }
  else {
    $status = "pending"
  }

  $evidence = '`' + $item.evidence + '`'
  $lines.Add("| $($item.category) | $($item.name) | $status | $evidence | $($item.notes) |")
}

$lines.Add("")
$lines.Add("## Release Gate Interpretation")
$lines.Add("")
$lines.Add('- `ready` means the expected local artifact or report exists and any machine-readable pass/fail field in that report is clean.')
$lines.Add('- `pending` means the release candidate needs another local or self-hosted runner pass, report cleanup, or manual release-owner confirmation before publication.')
$lines.Add('- Linux Ubuntu 20.04/22.04/24.04 x64 runtime packages remain handoff/dry-run evidence until a matching Linux runner completes build, package consumer validation, and release/package upload checks.')
$lines.Add('- ARM/SBSA, Jetson/L4T, and non-Ubuntu lines must remain unpublished until their dedicated package identities, runners or containers, and NVIDIA dependency strategy are modeled and validated.')
$lines.Add("- Large CUDA/cuDNN/TensorRT component packages should stay on GitHub Packages or GitHub Releases unless their size and redistribution terms are cleared for nuget.org.")
$lines.Add("- Hosted GitHub gates validate source, docs, managed packaging, and static workflow contracts; runtime package readiness requires local or self-hosted runtime artifacts.")

$markdownPath = Join-Path $outputRoot "release-candidate-checklist.md"
$lines | Set-Content -LiteralPath $markdownPath -Encoding utf8

Write-Host "Release candidate checklist written to $jsonPath"
Write-Host "Release candidate checklist written to $markdownPath"
