[CmdletBinding()]
param(
  [string]$RepositoryRoot,
  [string]$OutputDirectory
)

if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) {
  $scriptRoot = if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) { (Get-Location).Path } else { $PSScriptRoot }
  $RepositoryRoot = (Resolve-Path (Join-Path $scriptRoot "..")).Path
}

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
  $OutputDirectory = Join-Path $RepositoryRoot "artifacts\api-inventory"
}

$utf8 = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = $utf8
$OutputEncoding = $utf8

New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null

$manifestRoot = Join-Path $RepositoryRoot "native\manifests"
$nativeRoot = Join-Path $RepositoryRoot "native"

$manifestEntries = New-Object System.Collections.Generic.List[object]
foreach ($manifestPath in Get-ChildItem -Path $manifestRoot -Filter "*.manifest.json" -Recurse) {
  $document = Get-Content -LiteralPath $manifestPath.FullName -Raw -Encoding utf8 | ConvertFrom-Json
  foreach ($api in @($document.apis)) {
    $manifestEntries.Add([pscustomobject]@{
      Id = [string]$api.id
      EntryPoint = [string]$api.entryPoint
      Module = [string]$document.module
      VersionLine = [string]$document.versionLine
      ManualOverride = [bool]$api.manualOverride
      VersionGuard = [string]$api.versionGuard
      ManifestPath = $manifestPath.FullName.Substring($RepositoryRoot.Length + 1)
    })
  }
}

$sourceExports = New-Object System.Collections.Generic.List[object]
$exportPattern = [regex]'(?:JYPPX_C_API\s*\([^)]+\)|JYPPX_StatusCode|int|void|const\s+char\s*\*)\s+(?<name>jyppx_[A-Za-z0-9_]+)\s*\('
foreach ($sourcePath in Get-ChildItem -Path $nativeRoot -Include *.h,*.hpp,*.c,*.cc,*.cpp,*.inc -Recurse) {
  if ($sourcePath.FullName -match '\\generated\\') {
    continue
  }

  $text = Get-Content -LiteralPath $sourcePath.FullName -Raw -Encoding utf8
  foreach ($match in $exportPattern.Matches($text)) {
    $name = $match.Groups["name"].Value
    $module = if ($name -like "jyppx_trt*") { "tensorrt" } elseif ($name -like "jyppx_cuda*") { "cuda" } elseif ($name -like "jyppx_common*") { "common" } else { "unknown" }
    $line = if ($name -match '^jyppx_trt(?<line>[0-9]+)_') { $Matches.line } elseif ($module -eq "cuda") { "cuda" } elseif ($module -eq "common") { "common" } else { "" }
    $sourceExports.Add([pscustomobject]@{
      EntryPoint = $name
      Module = $module
      VersionLine = $line
      SourcePath = $sourcePath.FullName.Substring($RepositoryRoot.Length + 1)
    })
  }
}

$manifestByEntry = @{}
foreach ($entry in $manifestEntries) {
  $manifestByEntry[$entry.EntryPoint] = $entry
}

$sourceByEntry = @{}
foreach ($entry in $sourceExports) {
  if (-not $sourceByEntry.ContainsKey($entry.EntryPoint)) {
    $sourceByEntry[$entry.EntryPoint] = $entry
  }
}

$sourceWithoutManifest = @($sourceByEntry.Values | Where-Object { -not $manifestByEntry.ContainsKey($_.EntryPoint) } | Sort-Object Module, VersionLine, EntryPoint)
$manifestWithoutSource = @($manifestEntries | Where-Object { -not $sourceByEntry.ContainsKey($_.EntryPoint) } | Sort-Object Module, VersionLine, EntryPoint)

$moduleCounts = @($manifestEntries | Group-Object Module | Sort-Object Name | ForEach-Object {
  $groupName = $_.Name
  [pscustomobject]@{
    Module = $groupName
    ManifestCount = $_.Count
    NativeExportCount = @($sourceByEntry.Values | Where-Object { $_.Module -eq $groupName }).Count
  }
})

$lineCounts = @($manifestEntries | Group-Object Module, VersionLine | Sort-Object Name | ForEach-Object {
  $parts = $_.Name -split ', '
  $moduleName = $parts[0]
  $versionLine = $parts[1]
  [pscustomobject]@{
    Module = $moduleName
    VersionLine = $versionLine
    ManifestCount = $_.Count
    NativeExportCount = @($sourceByEntry.Values | Where-Object { $_.Module -eq $moduleName -and $_.VersionLine -eq $versionLine }).Count
  }
})

$report = [ordered]@{
  generatedAtUtc = [DateTime]::UtcNow.ToString("o")
  manifestApiCount = $manifestEntries.Count
  nativeExportCount = $sourceByEntry.Count
  sourceWithoutManifestCount = $sourceWithoutManifest.Count
  manifestWithoutSourceCount = $manifestWithoutSource.Count
  moduleCounts = $moduleCounts
  lineCounts = $lineCounts
  sourceWithoutManifest = $sourceWithoutManifest
  manifestWithoutSource = $manifestWithoutSource
}

$jsonPath = Join-Path $OutputDirectory "api-inventory.json"
$mdPath = Join-Path $OutputDirectory "api-inventory.md"
$report | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $jsonPath -Encoding utf8

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# API Inventory")
$lines.Add("")
$lines.Add("Generated by `eng/Export-ApiInventory.ps1`.")
$lines.Add("")
$lines.Add("## Summary")
$lines.Add("")
$lines.Add("- Manifest API records: $($manifestEntries.Count)")
$lines.Add("- Native C ABI exports found in source: $($sourceByEntry.Count)")
$lines.Add("- Source exports missing from manifest: $($sourceWithoutManifest.Count)")
$lines.Add("- Manifest entries missing from source: $($manifestWithoutSource.Count)")
$lines.Add("")
$lines.Add("## Module Counts")
$lines.Add("")
$lines.Add("| Module | Manifest | Native exports |")
$lines.Add("| --- | ---: | ---: |")
foreach ($item in $moduleCounts) {
  $lines.Add("| $($item.Module) | $($item.ManifestCount) | $($item.NativeExportCount) |")
}

$lines.Add("")
$lines.Add("## Version Line Counts")
$lines.Add("")
$lines.Add("| Module | Version line | Manifest | Native exports |")
$lines.Add("| --- | --- | ---: | ---: |")
foreach ($item in $lineCounts) {
  $lines.Add("| $($item.Module) | $($item.VersionLine) | $($item.ManifestCount) | $($item.NativeExportCount) |")
}

$lines.Add("")
$lines.Add("## Source Exports Missing From Manifest")
$lines.Add("")
if ($sourceWithoutManifest.Count -eq 0) {
  $lines.Add("None.")
}
else {
  foreach ($item in $sourceWithoutManifest) {
    $lines.Add("- `$($item.EntryPoint)` module=$($item.Module) line=$($item.VersionLine) source=$($item.SourcePath)")
  }
}

$lines.Add("")
$lines.Add("## Manifest Entries Missing From Source")
$lines.Add("")
if ($manifestWithoutSource.Count -eq 0) {
  $lines.Add("None.")
}
else {
  foreach ($item in $manifestWithoutSource) {
    $lines.Add("- `$($item.EntryPoint)` module=$($item.Module) line=$($item.VersionLine) manifest=$($item.ManifestPath)")
  }
}

Set-Content -LiteralPath $mdPath -Value $lines -Encoding utf8

Write-Host "API inventory report written to $jsonPath"
Write-Host "API inventory report written to $mdPath"

if ($manifestWithoutSource.Count -gt 0) {
  throw "API inventory found manifest entries without matching native source exports."
}
