[CmdletBinding()]
param(
  [string]$RepositoryRoot
)

if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) {
  $scriptRoot = if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) { (Get-Location).Path } else { $PSScriptRoot }
  $RepositoryRoot = (Resolve-Path (Join-Path $scriptRoot "..")).Path
}

$utf8 = [System.Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = $utf8
$OutputEncoding = $utf8

function Test-File {
  param(
    [string]$Path
  )

  return Test-Path -LiteralPath (Join-Path $RepositoryRoot $Path) -PathType Leaf
}

function Test-AnyFile {
  param(
    [string]$Directory,
    [string]$Filter
  )

  return @(Get-ChildItem -LiteralPath (Join-Path $RepositoryRoot $Directory) -Filter $Filter -ErrorAction SilentlyContinue).Count -gt 0
}

function Test-Directory {
  param(
    [string]$Path
  )

  return Test-Path -LiteralPath (Join-Path $RepositoryRoot $Path) -PathType Container
}

function New-ChecklistItem {
  param(
    [string]$Category,
    [string]$Name,
    [bool]$Ready,
    [string]$Evidence,
    [string]$Notes
  )

  return [pscustomobject]@{
    category = $Category
    name = $Name
    ready = $Ready
    evidence = $Evidence
    notes = $Notes
  }
}

$items = New-Object System.Collections.Generic.List[object]

$items.Add((New-ChecklistItem -Category "managed" -Name "Managed package artifact" -Ready (Test-AnyFile "artifacts\managed" "JYPPX.TensorRT.CSharp.API.*.nupkg") -Evidence "artifacts/managed/JYPPX.TensorRT.CSharp.API.*.nupkg" -Notes "Generated by dotnet pack."))
$items.Add((New-ChecklistItem -Category "interop" -Name "Binding generator comparison report" -Ready (Test-File "artifacts\interop-comparison\native-methods-comparison.md") -Evidence "artifacts/interop-comparison/native-methods-comparison.md" -Notes "Generated by Test-BindingGeneratorOutputs.ps1 or Export-NativeMethodsComparison.ps1."))
$items.Add((New-ChecklistItem -Category "interop" -Name "Generated API coverage report" -Ready (Test-File "artifacts\interop-comparison\generated-api-coverage.md") -Evidence "artifacts/interop-comparison/generated-api-coverage.md" -Notes "Generated by Test-BindingGeneratorOutputs.ps1 or Export-GeneratedApiCoverage.ps1."))
$items.Add((New-ChecklistItem -Category "runtime" -Name "Runtime distribution report" -Ready (Test-File "artifacts\runtime-distribution\runtime-distribution-report.md") -Evidence "artifacts/runtime-distribution/runtime-distribution-report.md" -Notes "Generated by Export-RuntimeDistributionReport.ps1."))
$items.Add((New-ChecklistItem -Category "runtime" -Name "Runtime delivery strategy" -Ready (Test-File "artifacts\runtime-distribution\runtime-delivery-strategy.md") -Evidence "artifacts/runtime-distribution/runtime-delivery-strategy.md" -Notes "Generated by Export-RuntimeDeliveryStrategy.ps1."))
$items.Add((New-ChecklistItem -Category "runtime" -Name "Split runtime package report" -Ready (Test-File "artifacts\runtime-distribution\split-runtime-packages-report.md") -Evidence "artifacts/runtime-distribution/split-runtime-packages-report.md" -Notes "Generated by Validate-SplitRuntimePackages.ps1."))
$items.Add((New-ChecklistItem -Category "runtime" -Name "Release gate summary" -Ready (Test-File "artifacts\runtime-distribution\release-gate-summary.md") -Evidence "artifacts/runtime-distribution/release-gate-summary.md" -Notes "Generated by Export-ReleaseGateSummary.ps1."))
$items.Add((New-ChecklistItem -Category "consumer" -Name "Package consumer validation summary" -Ready (Test-File "artifacts\package-consumer\package-consumer-validation-summary.md") -Evidence "artifacts/package-consumer/package-consumer-validation-summary.md" -Notes "Generated by Test-PackageConsumer.ps1."))
$items.Add((New-ChecklistItem -Category "docs" -Name "Public API bilingual documentation audit" -Ready (Test-File "artifacts\api-doc-audit\public-api-bilingual-documentation-audit.md") -Evidence "artifacts/api-doc-audit/public-api-bilingual-documentation-audit.md" -Notes "Generated by Test-PublicApiBilingualDocumentation.ps1."))
$items.Add((New-ChecklistItem -Category "docs" -Name "DocFX site output" -Ready (Test-File "docs\_site\index.html") -Evidence "docs/_site/index.html" -Notes "Generated by dotnet docfx docs/docfx.json."))
$items.Add((New-ChecklistItem -Category "linux" -Name "Linux dry-run handoff artifacts" -Ready (Test-Directory "artifacts\linux-dry-run") -Evidence "artifacts/linux-dry-run" -Notes "Linux remains dry-run-only until a real self-hosted Linux x64 runner validates build and pack."))
$items.Add((New-ChecklistItem -Category "workflow" -Name "Workflow contract report" -Ready (Test-File "artifacts\workflow-contracts\workflow-contract-report.md") -Evidence "artifacts/workflow-contracts/workflow-contract-report.md" -Notes "Generated by Test-WorkflowContracts.ps1."))

$manifestPath = Join-Path $RepositoryRoot "pack\runtime\runtime-packages.manifest.json"
$manifest = Get-Content -LiteralPath $manifestPath -Raw -Encoding utf8 | ConvertFrom-Json
$localValidated = @($manifest.packages | Where-Object { $_.validationState -eq "local-validated" }).Count
$pendingLocalValidation = @($manifest.packages | Where-Object { $_.validationState -eq "pending-local-validation" }).Count
$dryRunOnly = @($manifest.packages | Where-Object { $_.validationState -eq "dry-run-only" }).Count
$knownValidationStates = @("local-validated", "pending-local-validation", "dry-run-only")
$unknownValidationStates = @(
  $manifest.packages |
    Where-Object { $knownValidationStates -notcontains $_.validationState } |
    Select-Object -ExpandProperty validationState -Unique
)
$unknownStateNotes = if ($unknownValidationStates.Count -gt 0) {
  " Unknown validation state(s): $($unknownValidationStates -join ', ')."
} else {
  ""
}
$validationStateNotes = "$localValidated local-validated package(s), $pendingLocalValidation pending-local-validation package(s), $dryRunOnly dry-run-only package(s).$unknownStateNotes"
$items.Add((New-ChecklistItem -Category "runtime" -Name "Runtime validation state matrix" -Ready ($localValidated -ge 4 -and $dryRunOnly -ge 4 -and $unknownValidationStates.Count -eq 0) -Evidence "pack/runtime/runtime-packages.manifest.json" -Notes $validationStateNotes))

$outputRoot = Join-Path $RepositoryRoot "artifacts\release-candidate"
New-Item -ItemType Directory -Path $outputRoot -Force | Out-Null

$jsonPath = Join-Path $outputRoot "release-candidate-checklist.json"
$items | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $jsonPath -Encoding utf8

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Release Candidate Checklist")
$lines.Add("")
$lines.Add("Generated on: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
$lines.Add("")
$lines.Add("| Category | Check | Status | Evidence | Notes |")
$lines.Add("| --- | --- | --- | --- | --- |")
foreach ($item in $items) {
  $status = if ($item.ready) { "ready" } else { "pending" }
  $evidence = '`' + $item.evidence + '`'
  $lines.Add("| $($item.category) | $($item.name) | $status | $evidence | $($item.notes) |")
}

$lines.Add("")
$lines.Add("## Release Gate Interpretation")
$lines.Add("")
$lines.Add('- `ready` means the expected local artifact or report exists.')
$lines.Add('- `pending` means the release candidate needs another local or self-hosted runner pass before publication.')
$lines.Add('- Linux runtime packages must remain non-public until a real Linux self-hosted runner changes their validation state from `dry-run-only`.')
$lines.Add("- Large CUDA/cuDNN/TensorRT component packages should stay on GitHub Packages or GitHub Releases unless their size and redistribution terms are cleared for nuget.org.")
$lines.Add("- Hosted GitHub gates validate source, docs, managed packaging, and static workflow contracts; runtime package readiness requires local or self-hosted runtime artifacts.")

$markdownPath = Join-Path $outputRoot "release-candidate-checklist.md"
$lines | Set-Content -LiteralPath $markdownPath -Encoding utf8

Write-Host "Release candidate checklist written to $jsonPath"
Write-Host "Release candidate checklist written to $markdownPath"
