<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\\..\\src\\JYPPX.CudaSharp\\JYPPX.CudaSharp.csproj" />
    <ProjectReference Include="..\\..\\src\\JYPPX.TensorRtSharp\\JYPPX.TensorRtSharp.csproj" />
    <ProjectReference Include="..\\..\\src\\JYPPX.TensorRtSharp.Tools\\JYPPX.TensorRtSharp.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\samples\JYPPX.SampleSupport\TensorRtSampleSupport.cs" Link="JYPPX.SampleSupport\TensorRtSampleSupport.cs" />
    <Compile Include="..\..\samples\JYPPX.SampleSupport\TensorRtOnnxSample.cs" Link="JYPPX.SampleSupport\TensorRtOnnxSample.cs" />
    <Compile Include="..\..\samples\JYPPX.SampleSupport\TensorRtOnnxSample.Inputs.cs" Link="JYPPX.SampleSupport\TensorRtOnnxSample.Inputs.cs" />
    <Compile Include="..\..\samples\JYPPX.SampleSupport\TensorRtOnnxSample.References.cs" Link="JYPPX.SampleSupport\TensorRtOnnxSample.References.cs" />
  </ItemGroup>
</Project>
