<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Project="..\..\build\JYPPX.PublicSamplePackages.props" />

  <ItemGroup>
    <ProjectReference Include="..\_shared\JYPPX.TensorRtSharp.ApplicationTools\JYPPX.TensorRtSharp.ApplicationTools.csproj" />
  </ItemGroup>
</Project>
