<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <JYPPXPackageKind>bridge</JYPPXPackageKind>
    <IsPackable>true</IsPackable>
    <PackageId>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22.Bridge</PackageId>
    <Title>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt10.11.cuda12.9.cudnn9.22.Bridge</Title>
    <JYPPXRuntimeKey>win-x64-trt10.11-cuda12.9-cudnn9.22-bridge</JYPPXRuntimeKey>
    <PackageTags>TensorRT;CUDA;runtime;split-delivery;bridge</PackageTags>
  </PropertyGroup>
</Project>
