<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt11.0.cuda13.2.cudnn9.22.CudaCudnn</PackageId>
    <Title>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt11.0.cuda13.2.cudnn9.22.CudaCudnn</Title>
    <JYPPXRuntimeKey>win-x64-trt11.0-cuda13.2-cudnn9.22-cuda-cudnn</JYPPXRuntimeKey>
    <PackageTags>TensorRT;CUDA;runtime;split-delivery;cuda;cudnn</PackageTags>
  </PropertyGroup>
</Project>
