using Xunit;

namespace JYPPX.ProjectQuality.Tests;

public sealed class BridgePackageConsumerTests
{
    [Fact]
    public void BridgeOnlyConsumerScriptValidatesSplitBridgePackageWithoutFullVendorRuntime()
    {
        string script = ReadSource("eng", "Test-BridgePackageConsumer.ps1");

        Assert.Contains("[string]$SourceRuntimeKey = \"win-x64-trt11.0-cuda13.2-cudnn9.22\"", script);
        Assert.Contains("BridgePackageDirectory", script);
        Assert.Contains("Resolve-BridgeSplitPackage", script);
        Assert.Contains("Test-NupkgContainsBridgeAsset", script);
        Assert.Contains("LastWriteTime", script);
        Assert.Contains("Sort-Object LastWriteTime, Version -Descending", script);
        Assert.Contains("runtimes/$rid/native/$bridgeFileName", script);
        Assert.Contains("<PackageReference Include=\"$($ManagedPackage.Id)\"", script);
        Assert.Contains("<PackageReference Include=\"$($BridgePackage.Id)\"", script);
        Assert.Contains("BridgeRuntimeLayoutCopied", script);
        Assert.Contains("HighLevelWrapperSurfaceProbe.CreateSummary()", script);
        Assert.Contains("HighLevelWrapperSurface", script);
        Assert.Contains("WrapperSurfaceEvidenceKind", script);
        Assert.Contains("compile-surface-proof", script);
        Assert.Contains("ConsumerBuildConfiguration", script);
        Assert.Contains("RestoreSucceeded", script);
        Assert.Contains("BuildSucceeded", script);
        Assert.Contains("PackageConsumerValidationSucceeded", script);
        Assert.Contains("IsRuntimeExecutionProof", script);
        Assert.Contains("IsPackageConsumerRuntimeProof", script);
        Assert.Contains("CanPromoteRuntimeProof", script);
        Assert.Contains("CanPublishPublicly", script);
        Assert.Contains("CanCloseReleaseIssue", script);
        Assert.Contains("RuntimeProofBoundary", script);
        Assert.Contains("bridge-only consumer validates package layout, high-level wrapper compile surface, and dependency diagnostics", script);
        Assert.Contains("ParserSnapshotBoundary", script);
        Assert.Contains("Parser/ParserRefitter diagnostic snapshots and summaries are copied managed surface proof only", script);
        Assert.Contains("Get-NativeDependencyProbeClassification", script);
        Assert.Contains("ProbeDiagnostic", script);
        Assert.Contains("NativeDependencyStatus", script);
        Assert.Contains("NativeDependencyDiagnostic", script);
        Assert.Contains("NativeDependencyProbeLine", script);
        Assert.Contains("NativeDependencySkippedReason", script);
        Assert.Contains("VendorExceptionCode", script);
        Assert.Contains("IsNativeDependencyMissing", script);
        Assert.Contains("IsVendorStructuredException", script);
        Assert.Contains("missing-native-dependency", script);
        Assert.Contains("vendor-structured-exception", script);
        Assert.Contains("structured exception with code", script);
        Assert.Contains("DllNotFoundException", script);
        Assert.Contains("BadImageFormatException", script);
        Assert.Contains("TensorRtBuilder.GetPluginRegistryInventory", script);
        Assert.Contains("TensorRtBuilder.IsPluginCreatorRegistered", script);
        Assert.Contains("TensorRtBuilder.TryIsPluginCreatorRegistered", script);
        Assert.Contains("TensorRtPluginRegistryInventory.FindCreator", script);
        Assert.Contains("TensorRtPluginRegistryInventory.TryFindCreator", script);
        Assert.Contains("TensorRtPluginRegistryInventory.GetFieldSummaries", script);
        Assert.Contains("TensorRtPluginFieldSummary", script);
        Assert.Contains("TensorRtPluginFieldSummary.FieldName", script);
        Assert.Contains("TensorRtPluginFieldSummary.FieldType", script);
        Assert.Contains("TensorRtPluginFieldSummary.HasData", script);
        Assert.Contains("TensorRtPluginRegistryInventoryDiagnostics.EmptyFieldNameCount", script);
        Assert.Contains("TensorRtPluginRegistryInventoryDiagnostics.NegativeFieldLengthCount", script);
        Assert.Contains("plugin-inventory-field-metadata", script);
        Assert.Contains("TensorRtEnvironmentProbe.IsGlobalPluginRegistryAvailable", script);
        Assert.Contains("TensorRtEnvironmentProbe.TryIsGlobalPluginRegistryAvailable", script);
        Assert.Contains("TensorRtEnvironmentProbe.InitializeBuiltInPlugins", script);
        Assert.Contains("TensorRtOnnxParser.ParseWithWeightDescriptors", script);
        Assert.Contains("initializeBuiltInPlugins", script);
        Assert.Contains("parseWithWeightDescriptors", script);
        Assert.Contains("TensorRtEngine.HasImplicitBatchDimensionCompatibility", script);
        Assert.Contains("TensorRtBuilderConfig.SerializedPluginPathCountCompatibility", script);
        Assert.Contains("TensorRtLayer.GetRnnV2LayerCount", script);
        Assert.Contains("TensorRtLayer.GetRnnV2HiddenSize", script);
        Assert.Contains("TensorRtLayer.GetRnnV2MaxSequenceLength", script);
        Assert.Contains("TensorRtLayer.GetRnnV2Operation", script);
        Assert.Contains("TensorRtLayer.GetRnnV2Direction", script);
        Assert.Contains("TensorRtLayer.GetRnnV2InputMode", script);
        Assert.Contains("TensorRtRnnOperation", script);
        Assert.Contains("TensorRtRnnDirection", script);
        Assert.Contains("TensorRtRnnInputMode", script);
        Assert.Contains("engine-rnn-readonly-diagnostics", script);
        Assert.Contains("snapshotFindCreator", script);
        Assert.Contains("snapshotTryFindCreator", script);
        Assert.Contains("TensorRtLogger", script);
        Assert.Contains("TensorRtProfiler", script);
        Assert.Contains("TensorRtProgressMonitor", script);
        Assert.Contains("TensorRtLogger.EmitDiagnostic", script);
        Assert.Contains("TensorRtLogger.CallbackFailureCount", script);
        Assert.Contains("TensorRtLogger.LastCallbackException", script);
        Assert.Contains("TensorRtLogger.InterfaceInfo", script);
        Assert.Contains("TensorRtLogger.TryGetInterfaceInfo", script);
        Assert.Contains("TensorRtLogger.ApiLanguage", script);
        Assert.Contains("TensorRtLogger.TryGetApiLanguage", script);
        Assert.Contains("TensorRtApiLanguage", script);
        Assert.Contains("TensorRtProfiler.EmitDiagnostic", script);
        Assert.Contains("TensorRtProfiler.CallbackFailureCount", script);
        Assert.Contains("TensorRtProfiler.LastCallbackException", script);
        Assert.Contains("TensorRtProfiler.TryGetInterfaceInfo", script);
        Assert.Contains("TensorRtProfiler.ApiLanguage", script);
        Assert.Contains("TensorRtProfiler.TryGetApiLanguage", script);
        Assert.Contains("TensorRtErrorRecorderSnapshot", script);
        Assert.Contains("TensorRtErrorRecord", script);
        Assert.Contains("TensorRtRuntimeDiagnosticSnapshot", script);
        Assert.Contains("TensorRtRuntimeDiagnosticSnapshot.ToSummary", script);
        Assert.Contains("TensorRtRuntimeDiagnosticSummary", script);
        Assert.Contains("TensorRtRuntimeDiagnosticSummary.CopiedErrorRecordCount", script);
        Assert.Contains("TensorRtRuntimeDiagnosticSummary.RuntimeEvidenceKind", script);
        Assert.Contains("TensorRtRuntimeDiagnosticSummary.IsRuntimeExecutionProof", script);
        Assert.Contains("TensorRtRuntimeDiagnosticSummary.CanPromoteReleaseProof", script);
        Assert.Contains("TensorRtRuntimeDiagnosticSummary.CanPromoteRuntimeProof", script);
        Assert.Contains("TensorRtEngineDeploymentSummary", script);
        Assert.Contains("TensorRtEngineDeploymentSummary.CopiedTensorCount", script);
        Assert.Contains("TensorRtEngineDeploymentSummary.CanPromoteRuntimeProof", script);
        Assert.Contains("TensorRtBuilderConfigDeploymentSummary", script);
        Assert.Contains("TensorRtBuilderConfigDeploymentSummary.PluginToSerializeCount", script);
        Assert.Contains("TensorRtBuilderConfigDeploymentSummary.CanPromoteRuntimeProof", script);
        Assert.Contains("TensorRtExecutionContextDeploymentSummary", script);
        Assert.Contains("TensorRtExecutionContextDeploymentSummary.CopiedRuntimeDiagnosticCount", script);
        Assert.Contains("TensorRtExecutionContextDeploymentSummary.CanPromoteRuntimeProof", script);
        Assert.Contains("TensorRtSerializationConfigSummary", script);
        Assert.Contains("TensorRtSerializationConfigSummary.CanPromoteRuntimeProof", script);
        Assert.Contains("TensorRtRuntimeConfigSummary", script);
        Assert.Contains("TensorRtRuntimeConfigSummary.CanPromoteRuntimeProof", script);
        Assert.Contains("engineDeploymentSummary", script);
        Assert.Contains("builderConfigDeploymentSummary", script);
        Assert.Contains("executionContextDeploymentSummary", script);
        Assert.Contains("serializationConfigSummary", script);
        Assert.Contains("runtimeConfigSummary", script);
        Assert.Contains("runtimeDiagnosticSummary", script);
        Assert.Contains("runtimeDiagnosticSummaryText", script);
        Assert.Contains("TensorRtRuntime.GetDiagnosticSnapshot", script);
        Assert.Contains("runtime.GetDiagnosticSnapshot()", script);
        Assert.Contains("TensorRtRuntime.TryGetErrorRecorderSnapshot", script);
        Assert.Contains("TensorRtRuntime.HasLogger", script);
        Assert.Contains("TensorRtRuntime.ClearErrorRecorder", script);
        Assert.Contains("TensorRtRuntime.ClearGpuAllocator", script);
        Assert.Contains("JYPPX.*.xml documentation surfaces", script);
        Assert.Contains("JYPPX.CudaSharp.xml", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSnapshot", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSnapshot.ToSummary", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.CopiedDiagnosticCount", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.UsedVCPluginLibraryCount", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.DiagnosticSummaryLength", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.RuntimeEvidenceKind", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.IsRuntimeExecutionProof", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.CanPromoteReleaseProof", script);
        Assert.Contains("onnxParserDiagnosticSummary", script);
        Assert.Contains("onnxParserDiagnosticSummaryText", script);
        Assert.Contains("TensorRtOnnxModelSupportReport", script);
        Assert.Contains("TensorRtOnnxModelSupportReport.ToSummary", script);
        Assert.Contains("TensorRtOnnxModelSupportSummary", script);
        Assert.Contains("TensorRtOnnxModelSupportSummary.CopiedSubgraphCount", script);
        Assert.Contains("TensorRtOnnxModelSupportSummary.CopiedNodeCount", script);
        Assert.Contains("TensorRtOnnxModelSupportSummary.RuntimeEvidenceKind", script);
        Assert.Contains("TensorRtOnnxModelSupportSummary.IsRuntimeExecutionProof", script);
        Assert.Contains("TensorRtOnnxModelSupportSummary.CanPromoteReleaseProof", script);
        Assert.Contains("TensorRtOnnxModelSupportSummary.CanDeleteDeferredRecord", script);
        Assert.Contains("onnxModelSupportSummary", script);
        Assert.Contains("onnxModelSupportSummaryText", script);
        Assert.Contains("TensorRtOnnxParser.GetDiagnosticSnapshot", script);
        Assert.Contains("parser.GetDiagnosticSnapshot()", script);
        Assert.Contains("onnx-parser-diagnostic-snapshot", script);
        Assert.Contains("onnx-parser-diagnostic-summary", script);
        Assert.Contains("onnx-parser-diagnostic-snapshot;onnx-parser-diagnostic-summary;onnx-parser-layer-output-copied-metadata;onnx-parser-refitter-diagnostic-snapshot;onnx-parser-refitter-diagnostic-summary", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSnapshot", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSnapshot.ToSummary", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary.CopiedDiagnosticCount", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary.DiagnosticSummaryLength", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary.RuntimeEvidenceKind", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary.IsRuntimeExecutionProof", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary.CanPromoteReleaseProof", script);
        Assert.Contains("onnxParserRefitterDiagnosticSummary", script);
        Assert.Contains("onnxParserRefitterDiagnosticSummaryText", script);
        Assert.Contains("TensorRtOnnxParserRefitter.GetDiagnosticSnapshot", script);
        Assert.Contains("parserRefitter.GetDiagnosticSnapshot()", script);
        Assert.Contains("onnx-parser-refitter-diagnostic-snapshot", script);
        Assert.Contains("onnx-parser-refitter-diagnostic-summary", script);
        Assert.Contains("TensorRtRefitterDiagnosticSnapshot", script);
        Assert.Contains("TensorRtRefitterDiagnosticSnapshot.ToSummary", script);
        Assert.Contains("TensorRtRefitterDiagnosticSummary", script);
        Assert.Contains("TensorRtRefitterDiagnosticSummary.CopiedMissingNamedWeightCount", script);
        Assert.Contains("TensorRtRefitterDiagnosticSummary.CopiedAllNamedWeightCount", script);
        Assert.Contains("refitterDiagnosticSummary", script);
        Assert.Contains("refitterDiagnosticSummaryText", script);
        Assert.Contains("TensorRtRefitter.GetDiagnosticSnapshot", script);
        Assert.Contains("refitter.GetDiagnosticSnapshot()", script);
        Assert.Contains("TensorRtRefitter.TryGetErrorRecorderSnapshot", script);
        Assert.Contains("TensorRtRefitter.ClearErrorRecorder", script);
        Assert.Contains("TensorRtBuilder.HasLogger", script);
        Assert.Contains("TensorRtBuilder.HasErrorRecorder", script);
        Assert.Contains("TensorRtBuilder.ClearErrorRecorder", script);
        Assert.Contains("TensorRtBuilder.ClearGpuAllocator", script);
        Assert.Contains("TensorRtExecutionContext.SetProfiler", script);
        Assert.Contains("TensorRtExecutionContext.ClearProfiler", script);
        Assert.Contains("TensorRtExecutionContext.HasProfiler", script);
        Assert.Contains("TensorRtExecutionContext.HasNativeProfiler", script);
        Assert.Contains("TensorRtExecutionContext.HasErrorRecorder", script);
        Assert.Contains("TensorRtExecutionContext.ClearErrorRecorder", script);
        Assert.Contains("TensorRtExecutionContext.HasOutputAllocator", script);
        Assert.Contains("TensorRtExecutionContext.ClearOutputAllocator", script);
        Assert.Contains("TensorRtExecutionContext.HasTemporaryStorageAllocator", script);
        Assert.Contains("TensorRtExecutionContext.ClearTemporaryStorageAllocator", script);
        Assert.Contains("TensorRtExecutionContext.HasDebugListener", script);
        Assert.Contains("TensorRtExecutionContext.ClearDebugListener", script);
        Assert.Contains("TensorRtExecutionContext.TryGetOutputAllocatorInterfaceInfo", script);
        Assert.Contains("TensorRtExecutionContext.TryGetTemporaryStorageAllocatorInterfaceInfo", script);
        Assert.Contains("TensorRtExecutionContext.TryGetDebugListenerInterfaceInfo", script);
        Assert.Contains("TensorRtExecutionContext.GetCallbackStateSnapshot", script);
        Assert.Contains("TensorRtExecutionContext.TryGetCallbackStateSnapshot", script);
        Assert.Contains("TensorRtExecutionContext.ClearCallbackState", script);
        Assert.Contains("TensorRtExecutionContext.GetRuntimeDiagnosticSnapshot", script);
        Assert.Contains("TensorRtExecutionContext.GetCallbackAllocatorSafeControlSummary", script);
        Assert.Contains("TensorRtExecutionContextCallbackStateSnapshot", script);
        Assert.Contains("TensorRtExecutionContextCallbackStateSnapshot.HasOutputAllocator", script);
        Assert.Contains("TensorRtExecutionContextCallbackStateSnapshot.OutputAllocatorInterfaceInfoAvailable", script);
        Assert.Contains("TensorRtExecutionContextCallbackStateSnapshot.DebugListenerClearSupported", script);
        Assert.Contains("TensorRtExecutionContextCallbackStateSnapshot.IsComplete", script);
        Assert.Contains("TensorRtExecutionContextCallbackStateSnapshot.Diagnostic", script);
        Assert.Contains("TensorRtExecutionContextRuntimeDiagnosticSnapshot", script);
        Assert.Contains("TensorRtExecutionContextRuntimeDiagnosticSnapshot.ToSummary", script);
        Assert.Contains("TensorRtExecutionContextRuntimeDiagnosticSummary", script);
        Assert.Contains("TensorRtExecutionContextRuntimeDiagnosticSummary.CallbackStateLastStatus", script);
        Assert.Contains("contextRuntimeDiagnosticSummary", script);
        Assert.Contains("contextRuntimeDiagnosticSummaryText", script);
        Assert.Contains("TensorRtExecutionContextCallbackAllocatorSafeControlSummary", script);
        Assert.Contains("contextCallbackAllocatorSafeControlSummary", script);
        Assert.Contains("callbackAllocatorSafeControlSummaryText", script);
        Assert.Contains("CopiedInterfaceInfoCount", script);
        Assert.Contains("CallbackInvocationAttempted", script);
        Assert.Contains("execution-context-callback-allocator-safe-control-summary", script);
        Assert.Contains("TensorRtProgressMonitor.EmitDiagnostic", script);
        Assert.Contains("TensorRtProgressMonitor.CallbackFailureCount", script);
        Assert.Contains("TensorRtProgressMonitor.LastCallbackException", script);
        Assert.Contains("TensorRtProgressMonitor.TryGetInterfaceInfo", script);
        Assert.Contains("TensorRtProgressMonitor.ApiLanguage", script);
        Assert.Contains("TensorRtProgressMonitor.TryGetApiLanguage", script);
        Assert.Contains("TensorRtBuilderConfig.SetProgressMonitor", script);
        Assert.Contains("TensorRtBuilderConfig.ClearProgressMonitor", script);
        Assert.Contains("callback-diagnostics", script);
        Assert.Contains("callback-api-language-safe-controls", script);
        Assert.Contains("error-recorder-snapshot", script);
        Assert.Contains("logger-presence-safe-controls", script);
        Assert.Contains("error-recorder-snapshot;logger-presence-safe-controls;allocator-debug-listener-safe-controls;callback-interface-info-safe-controls;execution-context-callback-state-snapshot;execution-context-callback-allocator-safe-control-summary", script);
        Assert.Contains("allocator-debug-listener-safe-controls", script);
        Assert.Contains("callback-interface-info-safe-controls", script);
        Assert.Contains("execution-context-callback-state-snapshot", script);
        Assert.Contains("allocator-owner-dry-run-diagnostics", script);
        Assert.Contains("allocator-owner-native-dry-run-controls", script);
        Assert.Contains("allocator-owner-state-ledger-dry-run-controls", script);
        Assert.Contains("TensorRtAllocatorCallbackOwner", script);
        Assert.Contains("TensorRtAllocatorDryRunRequest", script);
        Assert.Contains("TensorRtAllocatorDryRunResult", script);
        Assert.Contains("TensorRtAllocatorNativeDryRunResult", script);
        Assert.Contains("TensorRtAllocatorOwnerStateDryRunResult", script);
        Assert.Contains("TensorRtAllocatorCallbackOwner.RunDryRunDiagnostic", script);
        Assert.Contains("TensorRtAllocatorCallbackOwner.RunNativeDryRunDiagnostic", script);
        Assert.Contains("TensorRtAllocatorCallbackOwner.RunNativeStateLedgerDryRunDiagnostic", script);
        Assert.Contains("output-allocator-attach-detach-design-gate", script);
        Assert.Contains("TensorRtOutputAllocatorAttachDetachDesignGate", script);
        Assert.Contains("TensorRtOutputAllocatorAttachDetachDesignGateResult", script);
        Assert.Contains("output-allocator-runtime-proof-precheck", script);
        Assert.Contains("TensorRtOutputAllocatorRuntimeProofPrecheck", script);
        Assert.Contains("TensorRtOutputAllocatorRuntimeProofPrecheckResult", script);
        Assert.Contains("LineSupportsOutputAllocator", script);
        Assert.Contains("AttachDetachDesignGateReady", script);
        Assert.Contains("StableNativeOwnerAddressReady", script);
        Assert.Contains("NoThrowNativeVTableReady", script);
        Assert.Contains("NativeVTableReady", script);
        Assert.Contains("OutputBufferOwnershipRuntimeReady", script);
        Assert.Contains("debug-listener-runtime-proof-precheck", script);
        Assert.Contains("debug-listener-attach-detach-design-gate", script);
        Assert.Contains("TensorRtDebugListenerAttachDetachDesignGate", script);
        Assert.Contains("TensorRtDebugListenerAttachDetachDesignGateResult", script);
        Assert.Contains("AttachControlAvailable", script);
        Assert.Contains("DetachClearControlAvailable", script);
        Assert.Contains("TensorRtDebugListenerRuntimeProofPrecheck", script);
        Assert.Contains("TensorRtDebugListenerRuntimeProofPrecheckResult", script);
        Assert.Contains("CanAttemptRuntimeProof", script);
        Assert.Contains("RuntimeProofBlocked", script);
        Assert.Contains("profiler-safe-controls", script);
        Assert.Contains("progress-monitor-safe-controls", script);
        Assert.Contains("CudaMemory.GetRangeAttribute", script);
        Assert.Contains("CudaMemory.GetRangeAttributes", script);
        Assert.Contains("CudaMemory.GetRangeAccessedByDevices", script);
        Assert.Contains("CudaMemory.GetRangeDiagnosticSummary", script);
        Assert.Contains("CudaMemoryRangeDiagnosticSummary", script);
        Assert.Contains("CudaMemoryRangeDiagnosticSummary.RuntimeEvidenceKind", script);
        Assert.Contains("CudaMemoryRangeDiagnosticSummary.IsRuntimeExecutionProof", script);
        Assert.Contains("CudaMemoryRangeDiagnosticSummary.CanPromoteReleaseProof", script);
        Assert.Contains("CudaMemoryRangeDiagnosticSummary.CanPromoteRuntimeProof", script);
        Assert.Contains("CudaGraphDiagnosticSummary", script);
        Assert.Contains("CudaGraphDiagnosticSummary.CopiedNodeSnapshotCount", script);
        Assert.Contains("CudaGraphDiagnosticSummary.CopiedEdgeSnapshotCount", script);
        Assert.Contains("CudaGraphDiagnosticSummary.RuntimeEvidenceKind", script);
        Assert.Contains("CudaGraphDiagnosticSummary.IsRuntimeExecutionProof", script);
        Assert.Contains("CudaGraphDiagnosticSummary.CanPromoteReleaseProof", script);
        Assert.Contains("CudaGraphDiagnosticSummary.CanPromoteRuntimeProof", script);
        Assert.Contains("CudaGraphExecDiagnosticSummary", script);
        Assert.Contains("CudaGraphExecDiagnosticSummary.CopiedNodeStateCount", script);
        Assert.Contains("CudaGraphExecDiagnosticSummary.SnapshotsWithNodeTokenCount", script);
        Assert.Contains("CudaGraphExecDiagnosticSummary.RuntimeEvidenceKind", script);
        Assert.Contains("CudaGraphExecDiagnosticSummary.IsRuntimeExecutionProof", script);
        Assert.Contains("CudaGraphExecDiagnosticSummary.CanPromoteReleaseProof", script);
        Assert.Contains("CudaGraphExecDiagnosticSummary.CanPromoteRuntimeProof", script);
        Assert.Contains("CudaDevice.GetGraphMemorySummary", script);
        Assert.Contains("CudaDevice.CurrentGraphMemorySummary", script);
        Assert.Contains("CudaDeviceGraphMemoryInfo.ToSummary", script);
        Assert.Contains("CudaDeviceGraphMemorySummary", script);
        Assert.Contains("CudaDeviceGraphMemorySummary.CopiedScalarCounterCount", script);
        Assert.Contains("CudaDeviceGraphMemorySummary.CurrentCountersWithinHighWatermarks", script);
        Assert.Contains("CudaDeviceGraphMemorySummary.RuntimeEvidenceKind", script);
        Assert.Contains("CudaDeviceGraphMemorySummary.IsRuntimeExecutionProof", script);
        Assert.Contains("CudaDeviceGraphMemorySummary.CanPromoteReleaseProof", script);
        Assert.Contains("CudaDeviceGraphMemorySummary.CanPromoteRuntimeProof", script);
        Assert.Contains("memoryRangeDiagnosticSummary", script);
        Assert.Contains("graphDiagnosticSummary", script);
        Assert.Contains("graphExecDiagnosticSummary", script);
        Assert.Contains("deviceGraphMemorySummary", script);
        Assert.Contains("getDeviceGraphMemorySummary", script);
        Assert.Contains("currentDeviceGraphMemorySummary", script);
        Assert.Contains("memory.Advise(offset, count, advice, device)", script);
        Assert.Contains("memory.PrefetchAsync(offset, count, destinationDevice, stream)", script);
        Assert.Contains("TensorRtEnvironmentProbe.ProbeNativeDependencies", script);
        Assert.Contains("EnvironmentProbe=Skipped", script);
        Assert.Contains("Skipped=True Reason=", script);
        Assert.Contains("$env:JYPPX_NATIVE_BRIDGE_PATH = $null", script);
        Assert.Contains("$env:JYPPX_ENABLE_DEVELOPMENT_PROBING = $null", script);
        Assert.Contains("Wrapper surface", script);
        Assert.Contains("Native dependency", script);
        Assert.Contains("Vendor SEH", script);
        Assert.Contains("native dependency diagnostic", script);
        Assert.DoesNotContain("PackageReference Include=\"$($RuntimePackage", script);
    }

    [Fact]
    public void SplitRuntimeEntrypointRunsBridgeConsumerForBridgeOnlyBuilds()
    {
        string script = ReadSource("eng", "Invoke-LocalSplitRuntimePackage.ps1");
        string collectScript = ReadSource("eng", "Collect-SplitRuntimeAssets.ps1");

        Assert.Contains("bridgeOnlySplitSet", script);
        Assert.Contains("Skipping full base runtime build for bridge-only split packaging", script);
        Assert.Contains("eng\\Test-BridgePackageConsumer.ps1", script);
        Assert.Contains("-BridgePackageDirectory", script);
        Assert.Contains("-SplitPackageKey", script);
        Assert.Contains("-BridgeConfiguration", script);
        Assert.Contains("Using bridge build output as split source assets root", collectScript);
        Assert.Contains("build-out\\$buildPreset\\bin\\$configuration", collectScript);
        Assert.Contains("[string]$BridgeConfiguration", collectScript);
        Assert.Contains("Test-Path -LiteralPath $stagedBridgePath -PathType Leaf", collectScript);
        Assert.Contains("[switch]$RunBridgeRuntimeSmoke", script);
        Assert.Contains("eng\\Test-BridgePackageRuntimeConsumer.ps1", script);
        Assert.Contains("-TensorRtRoot", script);
        Assert.Contains("-CudaRoot", script);
        Assert.Contains("-CudnnRoot", script);
        Assert.Contains("-OutputRoot", script);
    }

    [Fact]
    public void BridgeRuntimeConsumerExecutesIdentityRoundtripOutsideRepository()
    {
        string script = ReadSource("eng", "Test-BridgePackageRuntimeConsumer.ps1");

        Assert.Contains("Resolve-RuntimeRoots.ps1", script);
        Assert.Contains("Test-BridgePackageConsumer.ps1", script);
        Assert.Contains("Runtime proof consumer root must be outside the source repository", script);
        Assert.Contains("<PackageReference Include=\"$($managedPackage.Id)\"", script);
        Assert.Contains("<PackageReference Include=\"$($bridgePackage.Id)\"", script);
        Assert.DoesNotContain("<ProjectReference Include=", script);
        Assert.Contains("builder.BuildSerializedNetwork(network, config)", script);
        Assert.Contains("runtime.Deserialize(serializedEngine)", script);
        Assert.Contains("engine.CreateExecutionContext()", script);
        Assert.Contains("bindings.EnqueueAsync(stream, synchronize: true", script);
        Assert.Contains("IdentityOutputMatch=True", script);
        Assert.Contains("RuntimeSmoke=Passed", script);
        Assert.Contains("compatible-host-bridge-package-runtime", script);
        Assert.Contains("isRuntimeExecutionProof = $runtimeSmokePassed", script);
        Assert.Contains("isPackageConsumerRuntimeProof = $false", script);
        Assert.Contains("canPromoteCompatibleHostRuntimeProof = $runtimeSmokePassed", script);
        Assert.Contains("canPublishPublicly = $false", script);
        Assert.Contains("canCloseReleaseIssue = $false", script);
        Assert.Contains("stdoutSha256", script);
        Assert.Contains("stderrSha256", script);
        Assert.Contains("combinedSha256", script);
        Assert.Contains("Get-NvidiaHostMetadata", script);
        Assert.Contains("nativeAssets", script);
        Assert.Contains("Get-PackageSourceEvidence", script);
        Assert.Contains("packageSources = [ordered]@{", script);
        Assert.Contains("usesLocalPackageFeed", script);
        Assert.Contains("isPublicCleanPackageConsumerProof = $false", script);
        Assert.Contains("isPostPublishCleanConsumerProof = $false", script);
        Assert.Contains("publicFeedProof = $false", script);
        Assert.Contains("Local feed evidence is not public clean package-consumer or post-publish proof.", script);
    }

    [Fact]
    public void RuntimeSplitReadmeDocumentsBridgeOnlyConsumerValidation()
    {
        string readme = ReadSource("pack", "runtime-split", "README.md");

        Assert.Contains("Only project-owned native bridge packages are active", readme);
        Assert.Contains("contains exactly one native binary", readme);
        Assert.Contains("jyppxtrtbridge.dll", readme);
        Assert.Contains("libjyppxtrtbridge.so", readme);
        Assert.Contains("CUDA, cuDNN, TensorRT, NVRTC", readme);
        Assert.Contains("are never included", readme);
        Assert.Contains("Consumers install a matching NVIDIA stack", readme);
        Assert.Contains("Invoke-LocalSplitRuntimePackage.ps1", readme);
        Assert.Contains("-SplitPackageRole bridge", readme);
        Assert.Contains("Test-ExternalVendorRuntimePackagePolicy.ps1", readme);
        Assert.Contains("non-packable", readme);
        Assert.Contains("Test-BridgePackageConsumer.ps1", readme);
        Assert.Contains("bridge-only", readme);
        Assert.Contains("Test-BridgePackageRuntimeConsumer.ps1", readme);
        Assert.Contains("compatible system-installed NVIDIA dependencies", readme);
        Assert.Contains("real DebugListener attach/invoke/detach cycle", readme);
        Assert.Contains("source-tree", readme);
        Assert.Contains("local-package", readme);
        Assert.Contains("public-package", readme);
        Assert.Contains("post-publish", readme);
        Assert.Contains("not copied into this package inventory", readme);
        Assert.DoesNotContain("RuntimeEvidenceKind=", readme);
        Assert.DoesNotContain("IsRealCallbackRuntimeProof=", readme);
        Assert.DoesNotContain("runtime-smoke-skipped", readme);
    }

    private static string ReadSource(params string[] pathParts)
    {
        string path = Path.Combine(new[] { RepositoryPaths.Root }.Concat(pathParts).ToArray());
        return File.ReadAllText(path);
    }
}
