using Xunit;

namespace JYPPX.ProjectQuality.Tests;

public sealed class RuntimePackageReadinessTests
{
    [Fact]
    public void RuntimeReadinessScriptReportsFullVendorStateWithoutClaimingBridgeOnlyIsFullRuntimeReady()
    {
        string script = ReadSource("eng", "Test-RuntimePackageReadiness.ps1");

        Assert.Contains("artifacts\\package-readiness", script);
        Assert.Contains("managedPackage", script);
        Assert.Contains("bridgePackage", script);
        Assert.Contains("bridgeConsumer", script);
        Assert.Contains("probeDiagnostic", script);
        Assert.Contains("nativeDependencyStatus", script);
        Assert.Contains("nativeDependencyDiagnostic", script);
        Assert.Contains("nativeDependencyProbeLine", script);
        Assert.Contains("nativeDependencySkippedReason", script);
        Assert.Contains("vendorExceptionCode", script);
        Assert.Contains("native dependency fields were added", script);
        Assert.Contains("bridge consumer report does not include native dependency fields", script);
        Assert.Contains("isNativeDependencyMissing", script);
        Assert.Contains("isVendorStructuredException", script);
        Assert.Contains("highLevelWrapperSurface", script);
        Assert.Contains("wrapperSurfaceCapabilities", script);
        Assert.Contains("New-WrapperSurfaceCapabilityEvidence", script);
        Assert.Contains("engine-rnn-readonly-diagnostics", script);
        Assert.Contains("hasEngineRnnReadonlyDiagnostics", script);
        Assert.Contains("HasImplicitBatchDimensionCompatibility", script);
        Assert.Contains("SerializedPluginPathCountCompatibility", script);
        Assert.Contains("GetRnnV2LayerCount", script);
        Assert.Contains("GetRnnV2HiddenSize", script);
        Assert.Contains("GetRnnV2MaxSequenceLength", script);
        Assert.Contains("GetRnnV2Operation", script);
        Assert.Contains("GetRnnV2Direction", script);
        Assert.Contains("GetRnnV2InputMode", script);
        Assert.Contains("GetRnnV2CellState", script);
        Assert.Contains("GetRnnV2HiddenState", script);
        Assert.Contains("GetRnnV2SequenceLengths", script);
        Assert.Contains("GetRnnV2WeightsForGate", script);
        Assert.Contains("GetRnnV2BiasForGate", script);
        Assert.Contains("TensorRtRnnV2GateWeightsSnapshot", script);
        Assert.Contains("TensorRtRnnGateType", script);
        Assert.Contains("TensorRtRnnOperation", script);
        Assert.Contains("TensorRtRnnDirection", script);
        Assert.Contains("TensorRtRnnInputMode", script);
        Assert.Contains("splitPackages", script);
        Assert.Contains("splitCollectionPackage", script);
        Assert.Contains("splitCollectionConsumer", script);
        Assert.Contains("fullVendorInputs", script);
        Assert.Contains("fullRuntimePackage", script);
        Assert.Contains("fullPackageConsumer", script);
        Assert.Contains("runtimeExecution", script);
        Assert.Contains("runtimeProofStatus", script);
        Assert.Contains("runtimeProofDiagnostic", script);
        Assert.Contains("runtimeProofRequiredForRelease", script);
        Assert.Contains("New-RuntimeExecutionEvidence", script);
        Assert.Contains("runtimeProofBlockerOwnerAction", script);
        Assert.Contains("New-RuntimeProofBlockerOwnerAction", script);
        Assert.Contains("runtimeProofBlockerOwnerAction.status", script);
        Assert.Contains("cuda-driver-runtime-compatibility", script);
        Assert.Contains("blocked-by-cuda-driver, dependency-probe-only, build-only, precheck, design-gate", script);
        Assert.Contains("Export-ExternalRuntimeProofRecordTemplate.ps1", script);
        Assert.Contains("Test-ExternalRuntimeProofRecord.ps1", script);
        Assert.Contains("runtimeDeserializationDependencyDiagnostics", script);
        Assert.Contains("New-RuntimeDeserializationDependencyDiagnosticsEvidence", script);
        Assert.Contains("runtime-deserialization-dependency-diagnostics", script);
        Assert.Contains("RuntimeEvidenceKind=dependency-diagnostics", script);
        Assert.Contains("FullPackageConsumerReportPresent", script);
        Assert.Contains("FullPackageConsumerSmokeRequested", script);
        Assert.Contains("FullPackageConsumerSmokeResult", script);
        Assert.Contains("DependencyProbeOnly", script);
        Assert.Contains("BlockedByCudaDriver", script);
        Assert.Contains("PluginLibraryDependencyDiagnosticsComplete=False", script);
        Assert.Contains("LoadRuntimeOwnershipModeled=False", script);
        Assert.Contains("CanPromoteRuntimeProof=False", script);
        Assert.Contains("package readiness is not runtime execution proof", script);
        Assert.Contains("allocatorOwnerLedgerDesignGate", script);
        Assert.Contains("New-AllocatorOwnerLedgerDesignGateEvidence", script);
        Assert.Contains("allocator-owner-ledger-design-gate", script);
        Assert.Contains("hasDeferredRowEvidence", script);
        Assert.Contains("missingDeferredRows", script);
        Assert.Contains("allocator owner ledger design gate is documented", script);
        Assert.Contains("realCallbackTrampolineGate", script);
        Assert.Contains("New-RealCallbackTrampolineGateEvidence", script);
        Assert.Contains("real-callback-trampoline-gate", script);
        Assert.Contains("realCallbackRuntimeEvidenceKind", script);
        Assert.Contains("not-present", script);
        Assert.Contains("isRealCallbackRuntimeProof", script);
        Assert.Contains("design-gate-only", script);
        Assert.Contains("dry-run/copied-state evidence from real-callback-runtime", script);
        Assert.Contains("not proof that TensorRT callbacks are enabled", script);
        Assert.Contains("realCallbackRuntimeEvidenceSchema", script);
        Assert.Contains("New-RealCallbackRuntimeEvidenceSchema", script);
        Assert.Contains("real-callback-runtime-evidence-schema", script);
        Assert.Contains("allocatorOwnerInternalRuntimePrototype", script);
        Assert.Contains("New-AllocatorOwnerInternalRuntimePrototypeEvidence", script);
        Assert.Contains("allocator-owner-internal-runtime-prototype", script);
        Assert.Contains("outputAllocatorInternalRuntimeGate", script);
        Assert.Contains("New-OutputAllocatorInternalRuntimeGateEvidence", script);
        Assert.Contains("output-allocator-internal-runtime-gate", script);
        Assert.Contains("TensorRtOutputAllocatorRuntimeGate", script);
        Assert.Contains("RunInternalNotifyShapeRuntimeGate", script);
        Assert.Contains("RunInternalReallocateOutputRuntimeGate", script);
        Assert.Contains("GetInternalRuntimeGateSnapshot", script);
        Assert.Contains("TensorRtOutputAllocatorRuntimeGateResult", script);
        Assert.Contains("TensorRtOutputAllocatorInternalRuntimeGateCallback", script);
        Assert.Contains("OutputBufferPointerExposed", script);
        Assert.Contains("OutputBufferPointerProduced", script);
        Assert.Contains("internal-runtime-gate", script);
        Assert.Contains("gate-ready", script);
        Assert.Contains("outputAllocatorCallbackOwnerDesign", script);
        Assert.Contains("New-OutputAllocatorCallbackOwnerDesignEvidence", script);
        Assert.Contains("output-allocator-callback-owner-design", script);
        Assert.Contains("TensorRtOutputAllocatorCallbackOwner", script);
        Assert.Contains("TensorRtOutputAllocatorCallbackOwnerSnapshot", script);
        Assert.Contains("NativeLedgerAvailable", script);
        Assert.Contains("StateTransitionCount", script);
        Assert.Contains("LedgerAllocationCount", script);
        Assert.Contains("outputAllocatorAttachDetachDesignGate", script);
        Assert.Contains("New-OutputAllocatorAttachDetachDesignGateEvidence", script);
        Assert.Contains("output-allocator-attach-detach-design-gate", script);
        Assert.Contains("TensorRtOutputAllocatorAttachDetachDesignGate", script);
        Assert.Contains("TensorRtOutputAllocatorAttachDetachDesignGateResult", script);
        Assert.Contains("DesignGateReady", script);
        Assert.Contains("outputBufferOwnershipSafetyGate", script);
        Assert.Contains("New-OutputBufferOwnershipSafetyGateEvidence", script);
        Assert.Contains("output-buffer-ownership-safety-gate", script);
        Assert.Contains("TensorRtOutputBufferOwnershipSafetyGate", script);
        Assert.Contains("TensorRtOutputBufferOwnershipSafetyGateResult", script);
        Assert.Contains("SafetyGateReady", script);
        Assert.Contains("CopiedCurrentMemoryMetadataReady", script);
        Assert.Contains("CurrentMemoryReusePolicyReady", script);
        Assert.Contains("BorrowedPointerEscapeBlocked", script);
        Assert.Contains("OwnedDevicePointerReleasePolicyReady", script);
        Assert.Contains("ShapeNotificationOrderingReady", script);
        Assert.Contains("ReallocateOutputRuntimeReady", script);
        Assert.Contains("outputAllocatorRuntimeProofPrecheck", script);
        Assert.Contains("New-OutputAllocatorRuntimeProofPrecheckEvidence", script);
        Assert.Contains("output-allocator-runtime-proof-precheck", script);
        Assert.Contains("TensorRtOutputAllocatorRuntimeProofPrecheck", script);
        Assert.Contains("TensorRtOutputAllocatorRuntimeProofPrecheckResult", script);
        Assert.Contains("NativeLedgerDesignReady", script);
        Assert.Contains("LineSupportsOutputAllocator", script);
        Assert.Contains("AttachDetachDesignGateReady", script);
        Assert.Contains("AttachControlAvailable=False", script);
        Assert.Contains("DetachClearControlAvailable", script);
        Assert.Contains("ManagedOwnerStateMachineReady", script);
        Assert.Contains("StableNativeOwnerAddressReady", script);
        Assert.Contains("NoThrowNativeVTableReady", script);
        Assert.Contains("NativeVTableReady", script);
        Assert.Contains("DevicePointerLedgerRuntimeReady", script);
        Assert.Contains("StreamLifetimeReady", script);
        Assert.Contains("OutputBufferOwnershipSafetyGateReady", script);
        Assert.Contains("OutputBufferOwnershipRuntimeReady", script);
        Assert.Contains("debugListenerCallbackOwnerDesign", script);
        Assert.Contains("New-DebugListenerCallbackOwnerDesignEvidence", script);
        Assert.Contains("debug-listener-callback-owner-design", script);
        Assert.Contains("TensorRtDebugListenerCallbackOwner", script);
        Assert.Contains("TensorRtDebugListenerCallbackOwnerSnapshot", script);
        Assert.Contains("ProcessDebugTensorCount", script);
        Assert.Contains("DebugTensorMetadataCopied", script);
        Assert.Contains("DebugTensorPointerExposed", script);
        Assert.Contains("DebugTensorPointerProduced", script);
        Assert.Contains("BorrowedDebugTensorPointerEscaped", script);
        Assert.Contains("debugListenerAttachDetachDesignGate", script);
        Assert.Contains("New-DebugListenerAttachDetachDesignGateEvidence", script);
        Assert.Contains("debug-listener-attach-detach-design-gate", script);
        Assert.Contains("TensorRtDebugListenerAttachDetachDesignGate", script);
        Assert.Contains("TensorRtDebugListenerAttachDetachDesignGateResult", script);
        Assert.Contains("AttachControlAvailable", script);
        Assert.Contains("DetachClearControlAvailable", script);
        Assert.Contains("StableNativeOwnerAddressReady", script);
        Assert.Contains("NoThrowNativeVTableReady", script);
        Assert.Contains("design-gate-ready", script);
        Assert.Contains("debugListenerBorrowedTensorSafetyGate", script);
        Assert.Contains("New-DebugListenerBorrowedTensorSafetyGateEvidence", script);
        Assert.Contains("debug-listener-borrowed-tensor-safety-gate", script);
        Assert.Contains("TensorRtDebugListenerBorrowedTensorSafetyGate", script);
        Assert.Contains("TensorRtDebugListenerBorrowedTensorSafetyGateResult", script);
        Assert.Contains("BorrowedDebugTensorPointerEscapeBlocked=True", script);
        Assert.Contains("BorrowedDebugTensorLifetimeReady=False", script);
        Assert.Contains("BorrowedDebugTensorDataLifetimeReady=False", script);
        Assert.Contains("ProcessDebugTensorRuntimeReady=False", script);
        Assert.Contains("safety-gate-ready", script);
        Assert.Contains("debugListenerAttachVTableSafetyGate", script);
        Assert.Contains("New-DebugListenerAttachVTableSafetyGateEvidence", script);
        Assert.Contains("debug-listener-attach-vtable-safety-gate", script);
        Assert.Contains("TensorRtDebugListenerAttachVTableSafetyGate", script);
        Assert.Contains("TensorRtDebugListenerAttachVTableSafetyGateResult", script);
        Assert.Contains("AttachControlAvailable=False", script);
        Assert.Contains("StableNativeOwnerAddressReady=False", script);
        Assert.Contains("NoThrowNativeVTableReady=False", script);
        Assert.Contains("ExceptionToStatusMappingReady=False", script);
        Assert.Contains("hasDebugListenerAttachVTableSafetyGate", script);
        Assert.Contains("debugListenerNativeAttachNoThrowPreflight", script);
        Assert.Contains("New-DebugListenerNativeAttachNoThrowPreflightEvidence", script);
        Assert.Contains("debug-listener-native-attach-nothrow-preflight", script);
        Assert.Contains("TensorRtDebugListenerNativeAttachNoThrowPreflight", script);
        Assert.Contains("TensorRtDebugListenerNativeAttachNoThrowPreflightResult", script);
        Assert.Contains("PreflightReady", script);
        Assert.Contains("NativeAttachEntryLocated=False", script);
        Assert.Contains("NativeDetachEntryLocated=True", script);
        Assert.Contains("NoThrowVTableDesignReady=False", script);
        Assert.Contains("ExceptionToStatusMappingDesignReady=False", script);
        Assert.Contains("CanImplementNativeAttach=False", script);
        Assert.Contains("hasDebugListenerNativeAttachNoThrowPreflight", script);
        Assert.Contains("debugListenerNativeOwnerAddressDesignGate", script);
        Assert.Contains("New-DebugListenerNativeOwnerAddressDesignGateEvidence", script);
        Assert.Contains("debug-listener-native-owner-address-design-gate", script);
        Assert.Contains("TensorRtDebugListenerNativeOwnerAddressDesignGate", script);
        Assert.Contains("TensorRtDebugListenerNativeOwnerAddressDesignGateResult", script);
        Assert.Contains("DesignGateReady", script);
        Assert.Contains("NativeAttachNoThrowPreflightReady", script);
        Assert.Contains("StableNativeOwnerAddressDesignReady=False", script);
        Assert.Contains("NativeOwnerNonCopyableReady=False", script);
        Assert.Contains("NativeOwnerDisposeOrderReady=False", script);
        Assert.Contains("NativeOwnerReleaseHookReady=False", script);
        Assert.Contains("NativeOwnerInFlightDrainReady=False", script);
        Assert.Contains("NoThrowNativeDestructorReady=False", script);
        Assert.Contains("NativeOwnerLifecycleReady=False", script);
        Assert.Contains("hasDebugListenerNativeOwnerAddressDesignGate", script);
        Assert.Contains("debugListenerNativeNoThrowVTableDesignGate", script);
        Assert.Contains("New-DebugListenerNativeNoThrowVTableDesignGateEvidence", script);
        Assert.Contains("debug-listener-native-nothrow-vtable-design-gate", script);
        Assert.Contains("TensorRtDebugListenerNativeNoThrowVTableDesignGate", script);
        Assert.Contains("TensorRtDebugListenerNativeNoThrowVTableDesignGateResult", script);
        Assert.Contains("NativeOwnerAddressDesignGateReady", script);
        Assert.Contains("NativeNoThrowVTableDesignGateReady", script);
        Assert.Contains("NativeVTableTrampolineReady", script);
        Assert.Contains("CallbackExceptionCaptureReady=False", script);
        Assert.Contains("CallbackStatusMappingReady=False", script);
        Assert.Contains("CallbackInFlightAccountingReady=False", script);
        Assert.Contains("hasDebugListenerNativeNoThrowVTableDesignGate", script);
        Assert.Contains("debugListenerNativeNoThrowDestructor", script);
        Assert.Contains("New-DebugListenerNativeNoThrowDestructorEvidence", script);
        Assert.Contains("debug-listener-native-nothrow-destructor", script);
        Assert.Contains("TensorRtDebugListenerNativeNoThrowDestructor", script);
        Assert.Contains("TensorRtDebugListenerNativeNoThrowDestructorResult", script);
        Assert.Contains("RuntimeEvidenceKind=destructor-gate", script);
        Assert.Contains("NativeOwnerNonCopyableStorageReady=True", script);
        Assert.Contains("DestructorNoThrowScaffoldReady=True", script);
        Assert.Contains("DestructorExceptionEscapeBlocked=True", script);
        Assert.Contains("DestructorAddressExposed=False", script);
        Assert.Contains("DestructorPointerProduced=False", script);
        Assert.Contains("NoThrowNativeDestructorReady=True", script);
        Assert.Contains("destructor-gate-ready", script);
        Assert.Contains("hasDebugListenerNativeNoThrowDestructor", script);
        Assert.Contains("debugListenerNativeOwnerLifecycleGate", script);
        Assert.Contains("New-DebugListenerNativeOwnerLifecycleGateEvidence", script);
        Assert.Contains("debug-listener-native-owner-lifecycle-gate", script);
        Assert.Contains("TensorRtDebugListenerNativeOwnerLifecycleGate", script);
        Assert.Contains("TensorRtDebugListenerNativeOwnerLifecycleGateResult", script);
        Assert.Contains("RuntimeEvidenceKind=lifecycle-gate", script);
        Assert.Contains("NativeNoThrowDestructorGateReady=True", script);
        Assert.Contains("ManagedDisposeSnapshotReady=True", script);
        Assert.Contains("LifecycleScaffoldReady=True", script);
        Assert.Contains("ReleaseHookOrderingGateReady=True", script);
        Assert.Contains("DisposeIdempotencyGateReady=True", script);
        Assert.Contains("InFlightDrainGateReady=True", script);
        Assert.Contains("CallbackStateUnpinAfterDetachGateReady=True", script);
        Assert.Contains("DelegateUnpinAfterDetachGateReady=True", script);
        Assert.Contains("LifecycleAddressExposed=False", script);
        Assert.Contains("LifecyclePointerProduced=False", script);
        Assert.Contains("LifecycleGateReady=True", script);
        Assert.Contains("NativeVTableDesignReady=False", script);
        Assert.Contains("lifecycle-gate-ready", script);
        Assert.Contains("hasDebugListenerNativeOwnerLifecycleGate", script);
        Assert.Contains("debugListenerRuntimeProofPrecheck", script);
        Assert.Contains("New-DebugListenerRuntimeProofPrecheckEvidence", script);
        Assert.Contains("debug-listener-runtime-proof-precheck", script);
        Assert.Contains("TensorRtDebugListenerRuntimeProofPrecheck", script);
        Assert.Contains("TensorRtDebugListenerRuntimeProofPrecheckResult", script);
        Assert.Contains("LineSpecificAttachDetachReady", script);
        Assert.Contains("NativeVTableReady", script);
        Assert.Contains("BorrowedTensorSafetyGateReady", script);
        Assert.Contains("AttachVTableSafetyGateReady", script);
        Assert.Contains("NativeAttachNoThrowPreflightReady", script);
        Assert.Contains("NativeOwnerAddressDesignGateReady", script);
        Assert.Contains("NativeNoThrowDestructorGateReady", script);
        Assert.Contains("NativeOwnerLifecycleGateReady", script);
        Assert.Contains("LifecycleScaffoldReady", script);
        Assert.Contains("LifecycleAddressExposed", script);
        Assert.Contains("LifecyclePointerProduced", script);
        Assert.Contains("BorrowedDebugTensorPointerEscapeBlocked", script);
        Assert.Contains("BorrowedDebugTensorDataLifetimeReady", script);
        Assert.Contains("ProcessDebugTensorRuntimeReady", script);
        Assert.Contains("CanAttemptRuntimeProof=False", script);
        Assert.Contains("RuntimeProofBlocked=True", script);
        Assert.Contains("runtime-gate-precheck", script);
        Assert.Contains("precheck-ready", script);
        Assert.Contains("owner-design-gate", script);
        Assert.Contains("design-ready", script);
        Assert.Contains("internal-runtime-prototype", script);
        Assert.Contains("RunInternalSyncAllocatorRuntimePrototype", script);
        Assert.Contains("GetInternalRuntimePrototypeSnapshot", script);
        Assert.Contains("TensorRtAllocatorInternalRuntimePrototypeResult", script);
        Assert.Contains("TensorRtAllocatorInternalRuntimePrototypeCallback", script);
        Assert.Contains("RealCallbackRuntime=False", script);
        Assert.Contains("EvidenceKind=allocator-owner-internal-runtime-prototype", script);
        Assert.Contains("ReleaseHookCount", script);
        Assert.Contains("CallbackStatePinned", script);
        Assert.Contains("DelegatePinned", script);
        Assert.Contains("DisposeRequested", script);
        Assert.Contains("not proof", script);
        Assert.Contains("requiredSmokeMarkers", script);
        Assert.Contains("RealCallbackRuntime=True", script);
        Assert.Contains("EvidenceKind=real-callback-runtime", script);
        Assert.Contains("CallbackKind", script);
        Assert.Contains("InFlightCallbackCount", script);
        Assert.Contains("FullPackageConsumerReport", script);
        Assert.Contains("realCallbackRuntimeEvidence", script);
        Assert.Contains("New-RealCallbackRuntimeEvidence", script);
        Assert.Contains("callbackRuntimeEvidenceStatus", script);
        Assert.Contains("callbackRuntimeEvidenceKind", script);
        Assert.Contains("callbackRuntimeRuntimeEvidenceKind", script);
        Assert.Contains("callbackRuntimeIsProof", script);
        Assert.Contains("callbackRuntimeRequiredMarkers", script);
        Assert.Contains("callbackRuntimeMissingMarkers", script);
        Assert.Contains("callbackRuntimeMatchedLines", script);
        Assert.Contains("callbackRuntimeDiagnostic", script);
        Assert.Contains("full-package-consumer-report", script);
        Assert.Contains("historical consumer callback runtime report", script);
        Assert.Contains("missingSmokeMarkers", script);
        Assert.Contains("incomplete-real-callback-runtime", script);
        Assert.Contains("debugListenerCallbackProofGapReport", script);
        Assert.Contains("New-DebugListenerCallbackProofGapReportEvidence", script);
        Assert.Contains("debug-listener-callback-proof-gap-report", script);
        Assert.Contains("RuntimeEvidenceKind=proof-gap-report", script);
        Assert.Contains("PrimaryGapReason", script);
        Assert.Contains("RuntimeProofBlockerCategory", script);
        Assert.Contains("PackageConsumerRuntimeProofRequired", script);
        Assert.Contains("RuntimeInvocationRequired", script);
        Assert.Contains("EvidenceSource", script);
        Assert.Contains("NextOwnerAction", script);
        Assert.Contains("NoNonProofCallbackRuntimeMarker", script);
        Assert.Contains("proof-gap-report-ready", script);
        Assert.Contains("callback owner closure matrix must be complete", script);
        Assert.Contains("DebugListener callback proof gap report must be complete", script);
        Assert.Contains("$overallStatus = \"blocked\"", script);
        Assert.Contains("fullRuntimeStatus", script);
        Assert.Contains("readinessBlockers", script);
        Assert.Contains("New-ReadinessBlocker", script);
        Assert.Contains("missingAssets", script);
        Assert.Contains("missingAssetSummaryByKind", script);
        Assert.Contains("New-MissingAssetSummaryByKind", script);
        Assert.Contains("New-VendorRootDiagnostics", script);
        Assert.Contains("vendorRootDiagnostics", script);
        Assert.Contains("hasImportLibrariesOnly", script);
        Assert.Contains("development-library-only vendor layout", script);
        Assert.Contains("nextAction", script);
        Assert.Contains("suggestedCommand", script);
        Assert.Contains("isExternalInputRequired", script);
        Assert.Contains("evidenceKind", script);
        Assert.Contains("isBridgeOnlyEvidence", script);
        Assert.Contains("isFullRuntimeEvidence", script);
        Assert.Contains("isRuntimeExecutionEvidence", script);
        Assert.Contains("bridge-layout-wrapper-surface-dependency-probe", script);
        Assert.Contains("full-runtime-package-consumer-smoke", script);
        Assert.Contains("full-runtime-package-consumer-smoke-failed", script);
        Assert.Contains("full-runtime-package-consumer-smoke-driver-blocked", script);
        Assert.Contains("split-collection-package-consumer-smoke-failed", script);
        Assert.Contains("split-collection-package-consumer-smoke-driver-blocked", script);
        Assert.Contains("blocked-by-cuda-driver", script);
        Assert.Contains("expected vendor runtime asset(s) were not found", script);
        Assert.Contains("Test-RuntimePackageReadiness.ps1", script);
        Assert.Contains("FailOnBlocked", script);
        Assert.Contains("Get-BridgeConsumerEvidence", script);
        Assert.Contains("Get-SplitCollectionConsumerEvidence", script);
        Assert.Contains("Get-FullPackageConsumerEvidence", script);
        Assert.Contains("packageConsumerEvidenceKind", script);
        Assert.Contains("runtimeSmokeClassification", script);
        Assert.Contains("isDependencyProbeOnly", script);
        Assert.Contains("historical consumer evidence scope:", script);
        Assert.Contains("Runtime execution scope | Consumer status | Smoke requested | Smoke result | Classification", script);
        Assert.Contains("runtime-smoke-driver-blocked", script);
        Assert.Contains("dependency-probe-only", script);
        Assert.Contains("HighLevelWrapperSurface", script);
        Assert.Contains("hasPluginInventoryFieldMetadata", script);
        Assert.Contains("plugin-inventory-field-metadata", script);
        Assert.Contains("TensorRtPluginRegistryInventory.GetFieldSummaries", script);
        Assert.Contains("TensorRtPluginFieldSummary", script);
        Assert.Contains("TensorRtPluginFieldSummary.FieldName", script);
        Assert.Contains("TensorRtPluginFieldSummary.FieldType", script);
        Assert.Contains("TensorRtPluginFieldSummary.HasData", script);
        Assert.Contains("TensorRtPluginRegistryInventoryDiagnostics.EmptyFieldNameCount", script);
        Assert.Contains("TensorRtPluginRegistryInventoryDiagnostics.NegativeFieldLengthCount", script);
        Assert.Contains("hasOnnxParserDiagnosticReadiness", script);
        Assert.Contains("hasOnnxParserRefitterDiagnosticReadiness", script);
        Assert.Contains("onnx-parser-diagnostic-readiness", script);
        Assert.Contains("onnx-parser-refitter-diagnostic-readiness", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSnapshot.ErrorCount", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSnapshot.Diagnostics", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSnapshot.DiagnosticSummary", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSnapshot.UsedVCPluginLibraries", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSnapshot.IdentityOperatorSupported", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.CopiedDiagnosticCount", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.UsedVCPluginLibraryCount", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.DiagnosticSummaryLength", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.RuntimeEvidenceKind", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.IsRuntimeExecutionProof", script);
        Assert.Contains("TensorRtOnnxParserDiagnosticSummary.CanPromoteReleaseProof", script);
        Assert.Contains("TensorRtOnnxParser.GetDiagnosticSnapshot", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSnapshot.ErrorCount", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSnapshot.Diagnostics", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSnapshot.DiagnosticSummary", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary.CopiedDiagnosticCount", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary.DiagnosticSummaryLength", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary.RuntimeEvidenceKind", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary.IsRuntimeExecutionProof", script);
        Assert.Contains("TensorRtOnnxParserRefitterDiagnosticSummary.CanPromoteReleaseProof", script);
        Assert.Contains("TensorRtOnnxParserRefitter.GetDiagnosticSnapshot", script);
        Assert.Contains("hasErrorRecorderSnapshots", script);
        Assert.Contains("hasLoggerPresenceSafeControls", script);
        Assert.Contains("hasAllocatorDebugListenerSafeControls", script);
        Assert.Contains("hasCallbackInterfaceInfoSafeControls", script);
        Assert.Contains("hasCallbackApiLanguageSafeControls", script);
        Assert.Contains("callback-api-language-safe-controls", script);
        Assert.Contains("TensorRtLogger.ApiLanguage", script);
        Assert.Contains("TensorRtLogger.TryGetApiLanguage", script);
        Assert.Contains("TensorRtProfiler.ApiLanguage", script);
        Assert.Contains("TensorRtProfiler.TryGetApiLanguage", script);
        Assert.Contains("TensorRtProgressMonitor.ApiLanguage", script);
        Assert.Contains("TensorRtProgressMonitor.TryGetApiLanguage", script);
        Assert.Contains("TensorRtApiLanguage", script);
        Assert.Contains("callback-interface-info-safe-controls", script);
        Assert.Contains("execution-context-callback-state-snapshot", script);
        Assert.Contains("hasExecutionContextCallbackStateSnapshot", script);
        Assert.Contains("execution-context-callback-allocator-safe-control-summary", script);
        Assert.Contains("hasExecutionContextCallbackAllocatorSafeControlSummary", script);
        Assert.Contains("TensorRtExecutionContext.GetCallbackAllocatorSafeControlSummary", script);
        Assert.Contains("TensorRtExecutionContextCallbackAllocatorSafeControlSummary", script);
        Assert.Contains("bridge consumer callback allocator safe-control summary", script);
        Assert.Contains("copied-interface-info-safe-controls", script);
        Assert.Contains("hasAllocatorOwnerDryRunDiagnostics", script);
        Assert.Contains("allocator-owner-dry-run-diagnostics", script);
        Assert.Contains("hasAllocatorOwnerNativeDryRunControls", script);
        Assert.Contains("allocator-owner-native-dry-run-controls", script);
        Assert.Contains("hasAllocatorOwnerStateLedgerDryRunControls", script);
        Assert.Contains("allocator-owner-state-ledger-dry-run-controls", script);
        Assert.Contains("hasOutputAllocatorAttachDetachDesignGate", script);
        Assert.Contains("hasOutputBufferOwnershipSafetyGate", script);
        Assert.Contains("hasOutputAllocatorRuntimeProofPrecheck", script);
        Assert.Contains("hasDebugListenerCallbackOwnerDesign", script);
        Assert.Contains("hasDebugListenerAttachDetachDesignGate", script);
        Assert.Contains("hasDebugListenerBorrowedTensorSafetyGate", script);
        Assert.Contains("hasDebugListenerRuntimeProofPrecheck", script);
        Assert.Contains("allocator-owner-ledger-design.md", script);
        Assert.Contains("IGpuAllocator::free", script);
        Assert.Contains("IGpuAsyncAllocator::deallocateAsync", script);
        Assert.Contains("IDebugListener::processDebugTensor", script);
        Assert.Contains("TensorRtAllocatorCallbackOwner", script);
        Assert.Contains("RunDryRunDiagnostic", script);
        Assert.Contains("RunNativeDryRunDiagnostic", script);
        Assert.Contains("TensorRtAllocatorNativeDryRunResult", script);
        Assert.Contains("RunNativeStateLedgerDryRunDiagnostic", script);
        Assert.Contains("TensorRtAllocatorOwnerStateDryRunResult", script);
        Assert.Contains("TryGetOutputAllocatorInterfaceInfo", script);
        Assert.Contains("TryGetTemporaryStorageAllocatorInterfaceInfo", script);
        Assert.Contains("TryGetDebugListenerInterfaceInfo", script);
        Assert.Contains("TensorRtExecutionContext.GetCallbackStateSnapshot", script);
        Assert.Contains("TensorRtExecutionContext.ClearCallbackState", script);
        Assert.Contains("TensorRtExecutionContextCallbackStateSnapshot", script);
        Assert.Contains("OutputAllocatorInterfaceInfoAvailable", script);
        Assert.Contains("DebugListenerClearSupported", script);
        Assert.Contains("LastOperation", script);
        Assert.Contains("hasProfilerSafeControls", script);
        Assert.Contains("hasProgressMonitorSafeControls", script);
        Assert.Contains("hasCudaMemoryRange", script);
        Assert.Contains("Resolve-RuntimeRoots.ps1", script);
        Assert.Contains("split-package", script);
        Assert.Contains("$_.sourceRuntimeKey -eq $key -and $_.role -eq \"bridge\"", script);
        Assert.Contains("$fullRuntimeStatus = \"retired-not-required\"", script);
        Assert.Contains("host-vendor-inputs", script);
        Assert.Contains("do not copy them into a package", script);
        Assert.Contains("Test-BridgePackageRuntimeConsumer.ps1", script);
        Assert.DoesNotContain("New-ReadinessBlocker -Category \"full-runtime-package\"", script);
        Assert.DoesNotContain("New-ReadinessBlocker -Category \"full-package-consumer\"", script);
        Assert.DoesNotContain("New-ReadinessBlocker -Category \"split-collection-package\"", script);
        Assert.DoesNotContain("New-ReadinessBlocker -Category \"split-collection-consumer\"", script);
        Assert.DoesNotContain("& (Join-Path $RepositoryRoot \"eng\\Invoke-LocalRuntimePackage.ps1\")", script);
        Assert.DoesNotContain("& (Join-Path $RepositoryRoot \"eng\\Test-PackageConsumer.ps1\")", script);
    }

    [Fact]
    public void RuntimeReadinessMarkdownSeparatesBridgeEvidenceFromFullRuntimePackageEvidence()
    {
        string script = ReadSource("eng", "Test-RuntimePackageReadiness.ps1");

        Assert.Contains("| Runtime key | Managed | Bridge package | Bridge consumer | Bridge runtime | Packable roles | Legacy collection | Legacy collection consumer | Host NVIDIA inputs | Retired package | Historical consumer | Overall | Runtime proof |", script);
        Assert.Contains("bridge package consumer report was not found", script);
        Assert.Contains("bridge consumer native dependency", script);
        Assert.Contains("bridge consumer probe diagnostic", script);
        Assert.Contains("bridge consumer native dependency diagnostic", script);
        Assert.Contains("vendor-structured-exception=$($result.bridgeConsumer.isVendorStructuredException)", script);
        Assert.Contains("bridge consumer evidence scope", script);
        Assert.Contains("bridge consumer wrapper surface", script);
        Assert.Contains("bridge consumer wrapper capability status", script);
        Assert.Contains("bridge consumer plugin inventory field metadata", script);
        Assert.Contains("runtime-evidence=copied-plugin-field-metadata", script);
        Assert.Contains("bridge consumer onnx parser diagnostics", script);
        Assert.Contains("runtime-evidence=copied-parser-diagnostics", script);
        Assert.Contains("bridge consumer onnx parser-refitter diagnostics", script);
        Assert.Contains("runtime-evidence=copied-parser-refitter-diagnostics", script);
        Assert.Contains("bridge consumer callback api-language safe controls", script);
        Assert.Contains("runtime-evidence=scalar-copy-api-language", script);
        Assert.Contains("allocator owner ledger design gate:", script);
        Assert.Contains("allocator owner ledger diagnostic:", script);
        Assert.Contains("allocator owner internal runtime prototype:", script);
        Assert.Contains("allocator owner internal runtime prototype diagnostic:", script);
        Assert.Contains("output allocator internal runtime gate:", script);
        Assert.Contains("output allocator internal runtime gate diagnostic:", script);
        Assert.Contains("output allocator callback owner design:", script);
        Assert.Contains("output allocator callback owner design diagnostic:", script);
        Assert.Contains("output allocator attach/detach design gate:", script);
        Assert.Contains("output allocator attach/detach design gate diagnostic:", script);
        Assert.Contains("output buffer ownership safety gate:", script);
        Assert.Contains("output buffer ownership safety gate diagnostic:", script);
        Assert.Contains("output allocator runtime proof precheck:", script);
        Assert.Contains("output allocator runtime proof precheck diagnostic:", script);
        Assert.Contains("runtime proof status:", script);
        Assert.Contains("release-required=$($result.runtimeProofRequiredForRelease)", script);
        Assert.Contains("runtime proof blocker owner action:", script);
        Assert.Contains("Runtime proof owner action", script);
        Assert.Contains("runtime deserialization dependency diagnostics:", script);
        Assert.Contains("runtime deserialization dependency diagnostics diagnostic:", script);
        Assert.Contains("debug listener callback owner design:", script);
        Assert.Contains("debug listener callback owner design diagnostic:", script);
        Assert.Contains("debug listener attach/detach design gate:", script);
        Assert.Contains("debug listener attach/detach design gate diagnostic:", script);
        Assert.Contains("debug listener borrowed tensor safety gate:", script);
        Assert.Contains("debug listener borrowed tensor safety gate diagnostic:", script);
        Assert.Contains("debug listener attach/vtable safety gate:", script);
        Assert.Contains("debug listener attach/vtable safety gate diagnostic:", script);
        Assert.Contains("debug listener native attach/no-throw preflight:", script);
        Assert.Contains("debug listener native attach/no-throw preflight diagnostic:", script);
        Assert.Contains("debug listener native owner address design gate:", script);
        Assert.Contains("debug listener native owner address design gate diagnostic:", script);
        Assert.Contains("debug listener native no-throw vtable design gate:", script);
        Assert.Contains("debug listener native no-throw vtable design gate diagnostic:", script);
        Assert.Contains("debug listener native owner non-copyable storage:", script);
        Assert.Contains("debug listener native owner non-copyable storage diagnostic:", script);
        Assert.Contains("debug listener native no-throw destructor:", script);
        Assert.Contains("debug listener native no-throw destructor diagnostic:", script);
        Assert.Contains("debug listener native owner lifecycle gate:", script);
        Assert.Contains("debug listener native owner lifecycle gate diagnostic:", script);
        Assert.Contains("debug listener runtime proof precheck:", script);
        Assert.Contains("debug listener runtime proof precheck diagnostic:", script);
        Assert.Contains("debug listener callback proof gap report:", script);
        Assert.Contains("debug listener callback proof gap report diagnostic:", script);
        Assert.Contains("real callback trampoline gate:", script);
        Assert.Contains("real callback trampoline diagnostic:", script);
        Assert.Contains("real callback runtime evidence schema:", script);
        Assert.Contains("real callback runtime evidence:", script);
        Assert.Contains("Allocator owner ledger missing evidence", script);
        Assert.Contains("Allocator owner internal runtime prototype missing evidence", script);
        Assert.Contains("Output allocator internal runtime gate missing evidence", script);
        Assert.Contains("Output allocator callback owner design missing evidence", script);
        Assert.Contains("Output allocator attach/detach design gate missing evidence", script);
        Assert.Contains("Output allocator runtime proof precheck missing evidence", script);
        Assert.Contains("Debug listener callback owner design missing evidence", script);
        Assert.Contains("Debug listener attach/detach design gate missing evidence", script);
        Assert.Contains("Debug listener borrowed tensor safety gate missing evidence", script);
        Assert.Contains("Debug listener attach/vtable safety gate missing evidence", script);
        Assert.Contains("Debug listener native attach/no-throw preflight missing evidence", script);
        Assert.Contains("Debug listener native owner address design gate missing evidence", script);
        Assert.Contains("Debug listener native no-throw vtable design gate missing evidence", script);
        Assert.Contains("Debug listener native owner non-copyable storage missing evidence", script);
        Assert.Contains("Debug listener native no-throw destructor missing evidence", script);
        Assert.Contains("Debug listener native owner lifecycle gate missing evidence", script);
        Assert.Contains("Debug listener runtime proof precheck missing evidence", script);
        Assert.Contains("Debug listener callback proof gap report missing evidence", script);
        Assert.Contains("Real callback trampoline missing evidence", script);
        Assert.Contains("Real callback runtime missing evidence", script);
        Assert.Contains("ready=``$readyWrapperGroups``", script);
        Assert.Contains("missing=``$missingWrapperGroups``", script);
        Assert.Contains("full-runtime=$($result.bridgeConsumer.isFullRuntimeEvidence)", script);
        Assert.Contains("runtime-execution=$($result.bridgeConsumer.isRuntimeExecutionEvidence)", script);
        Assert.Contains("split collection package consumer report was not found", script);
        Assert.Contains("split collection package consumer report does not contain", script);
        Assert.Contains("full runtime package consumer report was not found", script);
        Assert.Contains("full runtime package consumer report does not contain", script);
        Assert.Contains("historical consumer evidence scope", script);
        Assert.Contains("historical consumer callback runtime report:", script);
        Assert.Contains("retired vendor package", script);
        Assert.Contains("publication-allowed=False", script);
        Assert.Contains("runtime execution smoke", script);
        Assert.Contains("| Runtime execution scope | Consumer status | Smoke requested | Smoke result | Classification | Exit code | Evidence kind | Runtime execution | Dependency probe only | Real callback proof | Diagnostic | Report |", script);
        Assert.Contains("legacy split collection consumer", script);
        Assert.Contains("| Split role | Package | Status | Version |", script);
        Assert.Contains("readiness blockers", script);
        Assert.Contains("| Blocker category | Status | Detail | Next action | Suggested command | External input | Evidence path |", script);
        Assert.Contains("Missing vendor kind", script);
        Assert.Contains("| Vendor root | Exists | DLLs | LIBs | Missing expected assets | Import-library-only | Diagnostic |", script);
        Assert.Contains("vendor blockers: none", script);
        Assert.Contains("Missing kind", script);
    }

    [Fact]
    public void RuntimeReadinessPreservesBridgeRuntimeCallbackStatePhaseAndStatus()
    {
        string script = ReadSource("eng", "Test-RuntimePackageReadiness.ps1");

        Assert.Contains("BridgeRuntimeConsumerReportRoot", script);
        Assert.Contains("Get-BridgeRuntimeConsumerEvidence", script);
        Assert.Contains("New-BridgeRuntimeCallbackStateEvidence", script);
        Assert.Contains("bridge-package-runtime-consumer-proof.json", script);
        Assert.Contains("callbackStateSnapshot", script);
        Assert.Contains("completeShape", script);
        Assert.Contains("partialShape", script);
        Assert.Contains("invalid-callback-state", script);
        Assert.Contains("missing-callback-state", script);
        Assert.Contains("bridgeRuntimeConsumer = $bridgeRuntimeConsumerEvidence", script);
        Assert.Contains("bridge runtime callback-state snapshot:", script);
        Assert.Contains("last-status=``$($result.bridgeRuntimeConsumer.callbackStateSnapshot.lastStatus)``", script);
        Assert.Contains("last-operation=``$($result.bridgeRuntimeConsumer.callbackStateSnapshot.lastOperation)``", script);
        Assert.Contains("bridge runtime callback-state diagnostic:", script);
        Assert.Contains("bridge runtime negative control:", script);
        Assert.Contains("It is not callback invocation, public-package, or post-publish proof", script);
    }

    private static string ReadSource(params string[] pathParts)
    {
        string path = Path.Combine(new[] { RepositoryPaths.Root }.Concat(pathParts).ToArray());
        return File.ReadAllText(path);
    }
}
