<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>JYPPX.TensorRT.CSharp.API.Runtime.linux-x64.ubuntu20.04.trt8.6.cuda12.1.cudnn8.9</PackageId>
    <Title>JYPPX.TensorRT.CSharp.API.Runtime.linux-x64.ubuntu20.04.trt8.6.cuda12.1.cudnn8.9</Title>
    <JYPPXRuntimeKey>linux-x64-ubuntu20.04-trt8.6-cuda12.1-cudnn8.9</JYPPXRuntimeKey>
  </PropertyGroup>
</Project>
