<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt11.0.cuda13.2.cudnn9.22.TensorRtBuilder.Sm100Sm120Ptx</PackageId>
    <Title>JYPPX.TensorRT.CSharp.API.Runtime.win-x64.trt11.0.cuda13.2.cudnn9.22.TensorRtBuilder.Sm100Sm120Ptx</Title>
    <JYPPXRuntimeKey>win-x64-trt11.0-cuda13.2-cudnn9.22-tensorrt-builder-sm100-sm120-ptx</JYPPXRuntimeKey>
    <PackageTags>TensorRT;CUDA;runtime;split-delivery;tensorrt;builder</PackageTags>
  </PropertyGroup>
</Project>
