<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;net6.0;net5.0;netcoreapp3.1;net471;net472;net48;net481</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>10</LangVersion>
    <RootNamespace>JYPPX.TensorRtSharp</RootNamespace>
    
    <!--Set NuGet Message-->
    <PackageId>JYPPX.TensorRT.CSharp.API </PackageId>
    <Title>TensorRtSharp</Title>
    <Version>0.0.5</Version>
    <Authors>Guojin Yan</Authors>
    <Company>Guojin Yan</Company>
    <Product>JYPPX.TensorRT.CSharp.API </Product>
    <Description></Description>
    <PackageProjectUrl>https://github.com/guojin-yan/TensorRT-CSharp-API.git</PackageProjectUrl>
    <RepositoryUrl>https://github.com/guojin-yan/TensorRT-CSharp-API.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageOutputPath>./../nuget</PackageOutputPath>
    <NeutralLanguage>zh</NeutralLanguage>
    <PackageReleaseNotes></PackageReleaseNotes>
    <RootNamespace>JYPPX.TensorRtSharp</RootNamespace>
    <AssemblyName>TensorRtSharp</AssemblyName>
    <PackageTags>TensorRtSharp;TensorRT;CSharp;C#-API;ONNX</PackageTags>
    <Copyright>Copyright © 2026 Yan Guojin. All Rights Reserved.</Copyright>
    <PackAsTool>False</PackAsTool>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageIcon>logo.jpg</PackageIcon>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>

  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\nuget\logo.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
