<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>YoloVision</AssemblyName>
    <RootNamespace>YoloVisionSample</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <JYPPXIncludeTensorRtOnnxSampleSupport>true</JYPPXIncludeTensorRtOnnxSampleSupport>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\JYPPX.CudaSharp\JYPPX.CudaSharp.csproj" />
    <ProjectReference Include="..\..\src\JYPPX.TensorRtSharp\JYPPX.TensorRtSharp.csproj" />
  </ItemGroup>
</Project>
