<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>RefittedPlan</AssemblyName>
    <RootNamespace>RefittedPlanSample</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <JYPPXIncludeTensorRtSampleSupport>true</JYPPXIncludeTensorRtSampleSupport>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
