name: manual-build-native

on:
  workflow_dispatch:
    inputs:
      configure_preset:
        description: CMake configure preset name
        required: true
        default: win-x64-dev
      build_preset:
        description: CMake build preset name
        required: true
        default: win-x64-dev-debug

jobs:
  build-native:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure
      run: cmake --preset "${{ github.event.inputs.configure_preset }}"

    - name: Build
      run: cmake --build --preset "${{ github.event.inputs.build_preset }}"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: native-${{ github.event.inputs.build_preset }}
        path: |
          build-out/**
          !build-out/**/*.obj

